export const irregularVerbs = [
  { en: [["be"], ["was", "were"], ["been"]], cs: ["být"] },
  { en: [["beat"], ["beat"], ["beaten"]], cs: ["porazit", "být", "překonat"] },
  { en: [["become"], ["became"], ["become"]], cs: ["stát se"] },
  { en: [["begin"], ["began"], ["begun"]], cs: ["začít"] },
  {
    en: [["bend"], ["bent"], ["bent"]],
    cs: ["ohnout se", "sklonit", "zahnout"]
  },
  { en: [["bite"], ["bit"], ["bitten"]], cs: ["kousat"] },
  { en: [["blow"], ["blew"], ["blown"]], cs: ["foukat"] },
  { en: [["break"], ["broke"], ["broken"]], cs: ["zlomit"] },
  { en: [["bring"], ["brought"], ["brought"]], cs: ["přinést"] },
  { en: [["build"], ["built"], ["built"]], cs: ["stavět"] },
  {
    en: [["burn"], ["burned", "burnt"], ["burned", "burnt"]],
    cs: ["hořet", "pálit"]
  },
  { en: [["buy"], ["bought"], ["bought"]], cs: ["kupovat"] },
  { en: [["catch"], ["caught"], ["caught"]], cs: ["chytit"] },
  { en: [["choose"], ["chose"], ["chosen"]], cs: ["vybrat"] },
  { en: [["come"], ["came"], ["come"]], cs: ["přijít"] },
  { en: [["cost"], ["cost"], ["cost"]], cs: ["stát (o ceně)"] },
  { en: [["cut"], ["cut"], ["cut"]], cs: ["krájet"] },
  { en: [["dig"], ["dug"], ["dug"]], cs: ["kopat"] },
  { en: [["do"], ["did"], ["done"]], cs: ["dělat"] },
  { en: [["draw"], ["drew"], ["drawn"]], cs: ["kreslit", "rýsovat"] },
  {
    en: [["dream"], ["dreamed", "dreamt"], ["dreamed", "dreamt"]],
    cs: ["snít"]
  },
  { en: [["drink"], ["drank"], ["drunk"]], cs: ["pít"] },
  { en: [["drive"], ["drove"], ["driven"]], cs: ["řídit (auto apod.)"] },
  { en: [["eat"], ["ate"], ["eaten"]], cs: ["jíst"] },
  { en: [["fall"], ["fell"], ["fallen"]], cs: ["padat"] },
  { en: [["feed"], ["fed"], ["fed"]], cs: ["krmit"] },
  { en: [["feel"], ["felt"], ["felt"]], cs: ["cítit", "cítit se"] },
  { en: [["fight"], ["fought"], ["fought"]], cs: ["bojovat"] },
  { en: [["find"], ["found"], ["found"]], cs: ["najít"] },
  {
    en: [["fit"], ["fit"], ["fit"]],
    cs: ["přizpůsobit", "padnout", "hodit se"]
  },
  { en: [["fly"], ["flew"], ["flown"]], cs: ["létat"] },
  { en: [["forget"], ["forgot"], ["forgotten"]], cs: ["zapomenout"] },
  { en: [["forgive"], ["forgave"], ["forgiven"]], cs: ["odpouštět"] },
  { en: [["freeze"], ["froze"], ["frozen"]], cs: ["zmrazit", "mrznout"] },
  { en: [["get"], ["got"], ["got"]], cs: ["dostat", "obdržet"] },
  { en: [["give"], ["gave"], ["given"]], cs: ["dát"] },
  { en: [["go"], ["went"], ["gone"]], cs: ["jít", "jet"] },
  { en: [["grow"], ["grew"], ["grown"]], cs: ["růst", "pěstovat"] },
  {
    en: [["hang"], ["hung", "hanged"], ["hung", "hanged"]],
    cs: ["pověsit", "viset"]
  },
  { en: [["have"], ["had"], ["had"]], cs: ["mít"] },
  { en: [["hear"], ["heard"], ["heard"]], cs: ["slyšet"] },
  { en: [["hide"], ["hid"], ["hidden"]], cs: ["skrýt", "schovat (se)"] },
  { en: [["hit"], ["hit"], ["hit"]], cs: ["narazit", "udeřit"] },
  { en: [["hold"], ["held"], ["held"]], cs: ["držet"] },
  { en: [["hurt"], ["hurt"], ["hurt"]], cs: ["zranit", "bolet"] },
  { en: [["keep"], ["kept"], ["kept"]], cs: ["držet", "zachovat"] },
  { en: [["know"], ["knew"], ["known"]], cs: ["vědět", "znát"] },
  { en: [["lead"], ["led"], ["led"]], cs: ["vést"] },
  {
    en: [["learn"], ["learned", "learnt"], ["learned", "learnt"]],
    cs: ["učit se"]
  },
  { en: [["leave"], ["left"], ["left"]], cs: ["nechat", "opustit"] },
  { en: [["lend"], ["lent"], ["lent"]], cs: ["půjčit někomu"] },
  { en: [["let"], ["let"], ["let"]], cs: ["nechat", "dovolit"] },
  { en: [["lie"], ["lay"], ["lain"]], cs: ["ležet", "položit"] },
  { en: [["light"], ["lit"], ["lit"]], cs: ["rozsvítit", "zapálit"] },
  { en: [["lose"], ["lost"], ["lost"]], cs: ["ztratit", "prohrát"] },
  { en: [["make"], ["made"], ["made"]], cs: ["dělat", "vyrábět"] },
  { en: [["mean"], ["meant"], ["meant"]], cs: ["mínit", "znamenat"] },
  { en: [["meet"], ["met"], ["met"]], cs: ["potkat"] },
  { en: [["pay"], ["paid"], ["paid"]], cs: ["platit"] },
  { en: [["put"], ["put"], ["put"]], cs: ["položit", "dát (kam)"] },
  { en: [["read"], ["read"], ["read"]], cs: ["číst"] },
  { en: [["ride"], ["rode"], ["ridden"]], cs: ["jet (na něčem)"] },
  { en: [["ring"], ["rang"], ["rung"]], cs: ["zvonit"] },
  { en: [["rise"], ["rose"], ["risen"]], cs: ["stoupat", "zvednout"] },
  { en: [["run"], ["ran"], ["run"]], cs: ["běžet"] },
  { en: [["say"], ["said"], ["said"]], cs: ["říkat"] },
  { en: [["see"], ["saw"], ["seen"]], cs: ["vidět"] },
  { en: [["sell"], ["sold"], ["sold"]], cs: ["prodávat"] },
  { en: [["send"], ["sent"], ["sent"]], cs: ["poslat"] },
  { en: [["set"], ["set"], ["set"]], cs: ["nastavit", "určit"] },
  { en: [["shake"], ["shook"], ["shaken"]], cs: ["třepat"] },
  { en: [["shine"], ["shone"], ["shone"]], cs: ["zářit", "svítit"] },
  { en: [["shoot"], ["shot"], ["shot"]], cs: ["střílet"] },
  { en: [["show"], ["showed"], ["shown"]], cs: ["ukázat"] },
  { en: [["shut"], ["shut"], ["shut"]], cs: ["zavřít"] },
  { en: [["sing"], ["sang"], ["sung"]], cs: ["zpívat"] },
  { en: [["sink"], ["sank"], ["sunk"]], cs: ["potopit", "klesat"] },
  { en: [["sit"], ["sat"], ["sat"]], cs: ["sědět", "sednout si"] },
  { en: [["sleep"], ["slept"], ["slept"]], cs: ["spát"] },
  { en: [["slide"], ["slid"], ["slid"]], cs: ["klouzat"] },
  {
    en: [["smell"], ["smelled", "smelt"], ["smelled", "smelt"]],
    cs: ["cítit (čichem)"]
  },
  { en: [["speak"], ["spoke"], ["spoken"]], cs: ["mluvit"] },
  { en: [["spend"], ["spent"], ["spent"]], cs: ["utratit", "strávit (čas)"] },
  {
    en: [["spill"], ["spilled", "spilt"], ["spilled", "spilt"]],
    cs: ["rozlít"]
  },
  {
    en: [["spoil"], ["spoilt", "spoiled"], ["spoilt", "spoiled"]],
    cs: ["zkazit", "zničit"]
  },
  { en: [["spread"], ["spread"], ["spread"]], cs: ["rozšířit", "roztáhnout"] },
  { en: [["stand"], ["stood"], ["stood"]], cs: ["stát", "postavit se"] },
  { en: [["steal"], ["stole"], ["stolen"]], cs: ["krást"] },
  {
    en: [["stick"], ["stuck"], ["stuck"]],
    cs: ["držet", "přilepit", "nalepit"]
  },
  { en: [["swim"], ["swam"], ["swum"]], cs: ["plavat"] },
  { en: [["take"], ["took"], ["taken"]], cs: ["vzít"] },
  { en: [["teach"], ["taught"], ["taught"]], cs: ["učit"] },
  { en: [["tear"], ["tore"], ["torn"]], cs: ["trhat", "roztrhat"] },
  { en: [["tell"], ["told"], ["told"]], cs: ["říct"] },
  { en: [["think"], ["thought"], ["thought"]], cs: ["myslet"] },
  { en: [["throw"], ["threw"], ["threw"]], cs: ["házet"] },
  { en: [["understand"], ["understood"], ["understood"]], cs: ["rozumět"] },
  { en: [["wake"], ["woke"], ["woken"]], cs: ["probudit (se)"] },
  { en: [["wear"], ["wore"], ["worn"]], cs: ["nosit", "oblékat"] },
  { en: [["win"], ["won"], ["won"]], cs: ["vyhrát"] },
  { en: [["write"], ["wrote"], ["written"]], cs: ["psát"] }
];
