import { v1 } from "uuid";

export let words = [
  {
    name: "Chapter 2",
    words: [
      {
        name: "Parts of a house",
        words: [
          { en: ["attic", "loft"], cs: ["podkroví", "půda"] },
          { en: ["balcony"], cs: ["balkon"] },
          { en: ["basement", "cellar"], cs: ["suterén", "sklep"] },
          { en: ["boiler room"], cs: ["technická místnost", "kotelna"] },
          { en: ["ceiling"], cs: ["strop"] },
          { en: ["chimney"], cs: ["komín"] },
          { en: ["dressing room"], cs: ["šatník"] },
          { en: ["door"], cs: ["dveře"] },
          { en: ["back door"], cs: ["zadní dveře"] },
          { en: ["front door"], cs: ["vstupní dveře"] },
          { en: ["downstairs"], cs: ["přízemí"] },
          { en: ["drive"], cs: ["příjezdová cesta"] },
          { en: ["fence"], cs: ["plot"] },
          { en: ["floor"], cs: ["patro", "podlaha"] },
          { en: ["garage"], cs: ["garáž"] },
          { en: ["underground garage"], cs: ["podzemní garáž"] },
          { en: ["garden"], cs: ["zahrada"] },
          { en: ["front garden"], cs: ["předzahrádka"] },
          { en: ["rear garden"], cs: ["zahrada za domem"] },
          { en: ["gate"], cs: ["vrata"] },
          { en: ["laundry"], cs: ["prádelna"] },
          { en: ["lawn"], cs: ["trávník"] },
          { en: ["letterbox"], cs: ["schránka na poštu"] },
          { en: ["roof"], cs: ["střecha"] },
          { en: ["staircase"], cs: ["schodiště"] },
          { en: ["stairs"], cs: ["schody"] },
          { en: ["toilet"], cs: ["toaleta"] },
          { en: ["upstairs"], cs: ["patro", "horní podlaží"] },
          { en: ["WC"], cs: ["WC"] },
          { en: ["window"], cs: ["okno"] },
        ],
      },
      {
        name: "Furniture and accessories",
        words: [
          {
            name: "In the whole house",
            words: [
              { en: ["blind"], cs: ["roleta", "žaluzie"] },
              { en: ["central heating"], cs: ["ústřední topení"] },
              { en: ["curtain"], cs: ["závěs", "záclona"] },
              { en: ["doorbell"], cs: ["zvonek u dveří"] },
              { en: ["doormat"], cs: ["rohožka"] },
              { en: ["electrical appliances"], cs: ["elektrický spotřebič"] },
              { en: ["fitted carpet"], cs: ["celoplošný koberec"] },
              { en: ["fitting"], cs: ["instalace", "armatura"] },
              { en: ["furniture"], cs: ["nábytek"] },
              { en: ["hall"], cs: ["předsíň"] },
              { en: ["household appliances"], cs: ["domácí spotřebiče"] },
              { en: ["light"], cs: ["lampa", "světlo"] },
              { en: ["light bulb"], cs: ["žárovka"] },
              { en: ["net curtain"], cs: ["záclona"] },
              { en: ["plant"], cs: ["rostlina"] },
              { en: ["radiator"], cs: ["radiátor", "topení"] },
              { en: ["vacuum cleaner"], cs: ["vysavač"] },
              { en: ["wallpaper"], cs: ["tapeta"] },
              { en: ["windowsill"], cs: ["okenní parapet"] },
            ],
          },
          {
            name: "Bathroom",
            words: [
              { en: ["bath"], cs: ["vana"] },
              { en: ["bathroom"], cs: ["koupelna"] },
              { en: ["mirror"], cs: ["zrcadlo"] },
              { en: ["shower"], cs: ["sprcha"] },
              { en: ["soap"], cs: ["mýdlo"] },
              { en: ["tap"], cs: ["kohoutek"] },
              { en: ["toothbrush"], cs: ["zubní kartáček"] },
              { en: ["towel"], cs: ["ručník"] },
              { en: ["washbasin"], cs: ["umyvadlo"] },
              { en: ["washing machine"], cs: ["pračka"] },
            ],
          },
          {
            name: "Bedroom",
            words: [
              { en: ["bed"], cs: ["postel"] },
              { en: ["bedding"], cs: ["ložní prádlo"] },
              { en: ["bedroom"], cs: ["ložnice"] },
              { en: ["bedside table"], cs: ["noční stolek"] },
              { en: ["blanket"], cs: ["přikrývka"] },
              { en: ["bookshelf"], cs: ["police na knihy"] },
              { en: ["chair"], cs: ["židle"] },
              { en: ["mattress"], cs: ["matrace"] },
              { en: ["pillow"], cs: ["polštář"] },
              { en: ["rug"], cs: ["kobereček"] },
              { en: ["sheet"], cs: ["prostěradlo"] },
              { en: ["shelf"], cs: ["police"] },
              { en: ["wardrobe"], cs: ["šatník"] },
            ],
          },
          {
            name: "Sitting room / living room",
            words: [
              { en: ["armchair"], cs: ["křeslo"] },
              { en: ["audio system", "stereo"], cs: ["stereo zařízení"] },
              { en: ["bookcase"], cs: ["knihovna"] },
              { en: ["carpet"], cs: ["koberec"] },
              { en: ["CD player"], cs: ["CD přehrávač"] },
              { en: ["coffee table"], cs: ["konferenční stolek"] },
              { en: ["couch", "sofa"], cs: ["pohovka"] },
              { en: ["cushion"], cs: ["polštářek"] },
              { en: ["dinning table"], cs: ["jídelní stůl"] },
              { en: ["fireplace"], cs: ["krb"] },
              { en: ["living room", "sitting room"], cs: ["obývací pokoj"] },
              { en: ["TV set"], cs: ["televize"] },
            ],
          },
          {
            name: "Kitchen",
            words: [
              { en: ["cooker"], cs: ["sporák"] },
              { en: ["electric cooker"], cs: ["elektrický sporák"] },
              { en: ["crockery"], cs: ["porcelánové (stolní) nádobí"] },
              { en: ["cupboard"], cs: ["skříňka"] },
              { en: ["cutlery"], cs: ["příbory"] },
              { en: ["dishwasher"], cs: ["myčka"] },
              { en: ["freezer"], cs: ["mrazák"] },
              { en: ["fridge"], cs: ["lednička"] },
              { en: ["kettle"], cs: ["konvice"] },
              { en: ["electric kettle"], cs: ["varná konvice"] },
              { en: ["kitchen"], cs: ["kuchyně"] },
              { en: ["kitchen table"], cs: ["kuchyňský stůl"] },
              { en: ["microwave oven"], cs: ["mikrovlnná trouba"] },
              { en: ["oven"], cs: ["trouba"] },
              { en: ["running water"], cs: ["tekoucí voda"] },
              { en: ["sink"], cs: ["dřez"] },
              { en: ["teapot"], cs: ["konvice na čaj"] },
            ],
          },
        ],
      },
      {
        name: "Types of houses and flats",
        words: [
          { en: ["apartment", "flat"], cs: ["byt"] },
          { en: ["bedsit"], cs: ["obývací ložnice"] },
          { en: ["double bedsit"], cs: ["obývací ložnice pro dvě osoby"] },
          { en: ["block of flats"], cs: ["bytový dům"] },
          { en: ["bungalow"], cs: ["přízemní domek"] },
          { en: ["cottage"], cs: ["chalupa", "chata"] },
          { en: ["detached house"], cs: ["samostatný dům"] },
          { en: ["farmhouse"], cs: ["usedlost", "zemědělské stavení"] },
          { en: ["high rise", "towerblock"], cs: ["věžák"] },
          { en: ["mansion"], cs: ["sídlo", "velký obytný dům"] },
          { en: ["office building"], cs: ["kancelářská budova"] },
          { en: ["residential building"], cs: ["obytná budova"] },
          { en: ["semi-detached house"], cs: ["dvojdomek"] },
          { en: ["skyscraper"], cs: ["mrakodrap"] },
          { en: ["studio flat"], cs: ["garsonka"] },
          { en: ["terraced house"], cs: ["řadový dům"] },
          { en: ["two-roomed flat"], cs: ["dvoupokojový byt"] },
        ],
      },
      {
        name: "Renting a flat",
        words: [
          {
            name: "Renting a flat",
            words: [
              { en: ["accommodation"], cs: ["ubytování"] },
              { en: ["bill"], cs: ["účet", "poplatek"] },
              { en: ["electricity bill"], cs: ["poplatek za elektřinu"] },
              { en: ["excluding bills"], cs: ["poplatky navíc"] },
              { en: ["including bills"], cs: ["poplatky zahrnuté v ceně"] },
              { en: ["telephone bill"], cs: ["účet za telefon"] },
              { en: ["estate agent"], cs: ["realitní makléř"] },
              { en: ["flatmate"], cs: ["spolubydlící (v bytě)"] },
              { en: ["for sale"], cs: ["na prodej"] },
              { en: ["landlady"], cs: ["domácí", "majitelka bytu"] },
              { en: ["landlord"], cs: ["domácí", "majitel bytu"] },
              { en: ["per month"], cs: ["měsíčně"] },
              { en: ["per week"], cs: ["týdně"] },
              { en: ["reasonable price"], cs: ["přijatelná cena"] },
              { en: ["rent"], cs: ["nájem"] },
              { en: ["roommate"], cs: ["spolubydlící (v pokoji)"] },
              { en: ["tenant"], cs: ["nájemník"] },
              { en: ["to let"], cs: ["k pronájmu"] },
            ],
          },
          {
            name: "Useful expressions",
            words: [
              {
                en: ["can afford something", "could afford something"],
                cs: ["moci si něco dovolit (finančně)"],
              },
              {
                en: ["find a place of your own"],
                cs: ["najít si vlastní bydlení"],
              },
              { en: ["let a flat"], cs: ["pronajmout byt"] },
              { en: ["pay in advance"], cs: ["zaplatit předem"] },
              { en: ["pay the bills"], cs: ["platit poplatky"] },
              { en: ["pay the rent"], cs: ["platit nájem"] },
              { en: ["rent a flat"], cs: ["pronajmout si byt"] },
              {
                en: ["share a flat", "share a room"],
                cs: ["bydlet společně v bytě", "bydlet společně v pokoji"],
              },
            ],
          },
        ],
      },
      {
        name: "Location",
        words: [
          {
            en: ["amenities", "facilities"],
            cs: ["vybavenost", "infrastruktura"],
          },
          { en: ["area"], cs: ["oblast"] },
          { en: ["capital", "capital city"], cs: ["hlavní město"] },
          { en: ["city"], cs: ["velkoměsto"] },
          { en: ["conveniently located"], cs: ["výhodně situovaný"] },
          { en: ["countryside", "the country", "village"], cs: ["venkov"] },
          { en: ["district"], cs: ["oblast"] },
          { en: ["easy access to something"], cs: ["snadný přístup k něčemu"] },
          { en: ["home town"], cs: ["domovské město"] },
          { en: ["housing estate"], cs: ["sídliště"] },
          { en: ["inhabitant", "resident"], cs: ["obyvatel"] },
          { en: ["location"], cs: ["poloha", "umístění"] },
          { en: ["neighbour"], cs: ["soused"] },
          { en: ["neighbourhood"], cs: ["okolí"] },
          { en: ["old town"], cs: ["staré město"] },
          { en: ["public transport"], cs: ["hromadná doprava"] },
          { en: ["rural"], cs: ["venkovský"] },
          { en: ["slums"], cs: ["slumy"] },
          { en: ["suburbs"], cs: ["předměstí"] },
          { en: ["tourist resort"], cs: ["turistické středisko"] },
          { en: ["tourist town"], cs: ["turistické město"] },
          { en: ["town"], cs: ["město"] },
          { en: ["underground station"], cs: ["stanice metra"] },
          { en: ["urban"], cs: ["městský"] },
          { en: ["view off"], cs: ["vyhlídka", "výhled"] },
        ],
      },
      {
        name: "Conditions and size",
        words: [
          {
            name: "Conditions and size",
            words: [
              { en: ["ancient"], cs: ["starožitný", "starodávný"] },
              { en: ["bare"], cs: ["holý"] },
              { en: ["bright"], cs: ["jasný"] },
              { en: ["comfortable"], cs: ["pohodlný"] },
              { en: ["uncomfortable"], cs: ["nepohodlný"] },
              { en: ["cosy"], cs: ["útulný"] },
              { en: ["fitted kitchen"], cs: ["kuchyně na míru"] },
              { en: ["furnished"], cs: ["zařízený"] },
              { en: ["unfurnished"], cs: ["nezařízený"] },
              { en: ["in bad condition"], cs: ["ve špatném stavu"] },
              { en: ["in good condition"], cs: ["v dobrém stavu"] },
              { en: ["modern"], cs: ["moderní"] },
              { en: ["recently renovated"], cs: ["nedávno zrenovovaný"] },
              { en: ["roomy", "spacious"], cs: ["prostorný"] },
              { en: ["tiny"], cs: ["maličký"] },
            ],
          },
          {
            name: "Verbs and expressions",
            words: [
              { en: ["collapse", "fall down"], cs: ["zhroutit se"] },
              { en: ["DIY", "Do it yourself"], cs: ["udělej si sám"] },
              {
                en: ["do up one's house", "redecorate"],
                cs: ["vylepšovat dům", "nově vymalovat"],
              },
            ],
          },
        ],
      },
      {
        name: "Housework",
        words: [
          {
            name: "Verbs",
            words: [
              { en: ["clean"], cs: ["mýt", "čistit"] },
              { en: ["commute"], cs: ["dojíždět do práce"] },
              { en: ["cook"], cs: ["vařit"] },
              { en: ["vacuum"], cs: ["luxovat"] },
            ],
          },
          {
            name: "Useful expressions",
            words: [
              { en: ["be at home", "be in home"], cs: ["být doma"] },
              { en: ["clean the bathroom"], cs: ["umýt koupelnu"] },
              { en: ["clean the floors"], cs: ["umýt podlahy"] },
              { en: ["clean the windows"], cs: ["umýt okna"] },
              { en: ["clean up the mess"], cs: ["uklidit nepořádek"] },
              { en: ["do the cooking"], cs: ["vařit"] },
              {
                en: ["do the dishes", "do the washing-up"],
                cs: ["mýt nádobí"],
              },
              {
                en: ["do the housework", "do household jobs"],
                cs: ["dělat domácí práce"],
              },
              { en: ["do the ironing"], cs: ["žehlit"] },
              { en: ["do the shopping"], cs: ["nakupovat"] },
              { en: ["do the washing"], cs: ["prát"] },
              { en: ["feel homesick"], cs: ["stýskat si po domově"] },
              { en: ["get home"], cs: ["dostat se domů"] },
              { en: ["leave the house"], cs: ["odejít z domu"] },
              { en: ["lock the door"], cs: ["zamknout dveře"] },
              { en: ["make the beds"], cs: ["stlát postele"] },
              { en: ["move house"], cs: ["přestěhovat se"] },
              { en: ["move in"], cs: ["nastěhovat se"] },
              { en: ["move out"], cs: ["vystěhovat se"] },
              { en: ["put away one's clothes"], cs: ["uklidit si oblečení"] },
              { en: ["see somebody home"], cs: ["vyprovodit někoho domů"] },
              { en: ["stay in"], cs: ["zůstat doma"] },
              { en: ["stay out"], cs: ["zůstat venku"] },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Chapter 3",
    words: [
      {
        name: "Types of schools",
        audio: [6],
        words: [
          { en: ["academy"], cs: ["akademie"], audio: [7] },
          {
            en: ["elementary school", "primary school"],
            cs: ["základní škola"],
            audio: [8, 9],
          },
          {
            en: ["high school", "secondary school"],
            cs: ["střední škola"],
            audio: [10, 11],
          },
          { en: ["independent school"], cs: ["soukromá škola"], audio: [12] },
          {
            en: ["kindergarden", "nursery school"],
            cs: ["mateřská škola"],
            audio: [13],
          },
          {
            en: ["middle school", "junior high school"],
            cs: ["střední škola"],
            audio: [14],
          },
          {
            en: ["mixed school", "co-educational school"],
            cs: ["koedukační škola"],
            audio: [15, 16],
          },
          {
            en: ["private school", "public school"],
            cs: ["soukromá škola"],
            audio: [17],
          },
          {
            en: ["single-sex school"],
            cs: ["chlapecká nebo dívčí škola"],
            audio: [18],
          },
          {
            en: ["state school", "public school"],
            cs: ["státní škola"],
            audio: [19],
          },
          { en: ["university"], cs: ["univerzita"], audio: [20] },
          {
            en: ["vocational school"],
            cs: ["učňovská škola", "odborná škola"],
            audio: [21],
          },
        ],
      },
      {
        name: "Places in a school",
        audio: [22],
        words: [
          {
            en: ["canteen", "dining room"],
            cs: ["školní jídelna"],
            audio: [23],
          },
          { en: ["classroom"], cs: ["třída"], audio: [24] },
          {
            en: ["common room"],
            cs: ["studovna", "místnost pro odpočinek"],
            audio: [25],
          },
          { en: ["computer room"], cs: ["počítačová učebna"], audio: [26] },
          { en: ["corridor"], cs: ["chodba"], audio: [27] },
          { en: ["gym"], cs: ["tělocvična"], audio: [28] },
          { en: ["headmaster's office"], cs: ["ředitelna"], audio: [29] },
          { en: ["laboratory", "lab"], cs: ["laboratoř"], audio: [30, 31] },
          { en: ["library"], cs: ["knihovna"], audio: [32] },
          { en: ["office"], cs: ["kabinet", "kancelář"], audio: [33] },
          { en: ["playground"], cs: ["hřiště"], audio: [34] },
          {
            en: ["science lab"],
            cs: ["učebna fyziky", "učebna biologie", "učebna chemie"],
            audio: [35],
          },
          { en: ["sports field"], cs: ["sportovní hřiště"], audio: [36] },
          { en: ["staffroom"], cs: ["sborovna"], audio: [37] },
        ],
      },
      {
        name: "People in a school",
        audio: [38],
        words: [
          { en: ["classmate"], cs: ["spolužák"], audio: [39] },
          { en: ["collage student"], cs: ["student"], audio: [40] },
          {
            en: ["deputy head", "assistant principal"],
            cs: ["zástupce ředitele"],
            audio: [41],
          },
          { en: ["examiner"], cs: ["zkoušející"], audio: [42] },
          { en: ["form teacher"], cs: ["třídní učitel"], audio: [43] },
          {
            en: ["headmaster", "head teacher", "principal"],
            cs: ["ředitel"],
            audio: [44],
          },
          {
            en: ["headmistress", "head teacher", "principal"],
            cs: ["ředitelka"],
            audio: [45],
          },
          { en: ["lacturer"], cs: ["přednášející", "lektor"], audio: [46] },
          { en: ["professor"], cs: ["profesor"], audio: [47] },
          {
            en: ["schoolboy", "pupil"],
            cs: ["školák", "žák"],
            audio: [48, 49],
          },
          {
            en: ["schoolgirl", "pupil"],
            cs: ["školačka", "žačka"],
            audio: [50],
          },
          { en: ["schoolmate"], cs: ["spolužák ze školy"], audio: [51] },
          { en: ["secretary"], cs: ["sekretář", "sekretářka"], audio: [52] },
          { en: ["student"], cs: ["student"], audio: [53] },
          { en: ["teacher"], cs: ["učitel"], audio: [54] },
          { en: ["teaching staff"], cs: ["pedagogický sbor"], audio: [55] },
          {
            en: ["university student"],
            cs: ["student univerzity"],
            audio: [56],
          },
        ],
      },
      {
        name: "School subjects",
        audio: [57],
        words: [
          { en: ["Art"], cs: ["umění"], audio: [58] },
          { en: ["Biology"], cs: ["biologie"], audio: [59] },
          { en: ["Chemistry"], cs: ["chemie"], audio: [60] },
          {
            en: ["Civic studies", "Civics"],
            cs: ["občanská výchova"],
            audio: [61],
          },
          { en: ["club"], cs: ["klub", "kroužek"], audio: [62] },
          {
            en: ["Czech language and literature"],
            cs: ["český jazyk a literatura"],
            audio: [63],
          },
          {
            en: ["English language and literature"],
            cs: ["anglický jazyk a literatura"],
            audio: [64],
          },
          { en: ["foreign languages"], cs: ["cizí jazyky"], audio: [65] },
          { en: ["Geography"], cs: ["zeměpis"], audio: [66] },
          { en: ["humanities"], cs: ["humanitní předměty"], audio: [67] },
          { en: ["History"], cs: ["dějepis"], audio: [68] },
          {
            en: [
              "Information and Communication Technology",
              "Information Technology",
              "ICT",
              "IT",
            ],
            cs: ["informatika"],
            audio: [69, 70, 71, 72],
          },
          { en: ["Mathematics", "Maths"], cs: ["matematika"], audio: [73] },
          { en: ["Music"], cs: ["hudba"], audio: [74] },
          {
            en: ["Physical Education", "PE"],
            cs: ["tělesná výchova"],
            audio: [75],
          },
          { en: ["Physics"], cs: ["fyzika"], audio: [76] },
          {
            en: ["Religious Education", "RE"],
            cs: ["výchova k náboženství"],
            audio: [77],
          },
          { en: ["Science"], cs: ["přírodní vědy"], audio: [78] },
          { en: ["subject"], cs: ["předmět"], audio: [79] },
        ],
      },
      {
        name: "School objects",
        audio: [80],
        words: [
          { en: ["blackboard"], cs: ["tabule"] },
          { en: ["blackboard marker"], cs: ["fix na tabuli"] },
          { en: ["board"], cs: ["tabule"] },
          { en: ["calculator"], cs: ["kalkulačka"] },
          { en: ["chalk"], cs: ["křída"] },
          { en: ["copybook", "notebook"], cs: ["sešit"] },
          { en: ["coursebook", "textbook"], cs: ["učebnice"] },
          { en: ["duster"], cs: ["houba", "utěrka na tabuli"] },
          { en: ["exercise book", "workbook"], cs: ["sešit"] },
          { en: ["file"], cs: ["pořadač", "šanon"] },
          { en: ["folder"], cs: ["desky"] },
          { en: ["interactive whiteboard"], cs: ["interaktivní tabule"] },
          { en: ["locker"], cs: ["zamykací skříňka"] },
          { en: ["PE kit"], cs: ["cvičební úbor"] },
          { en: ["pen"], cs: ["pero", "propisovačka"] },
          { en: ["pencil"], cs: ["tužka"] },
          { en: ["pencil case"], cs: ["penál"] },
          { en: ["pencil sharpener"], cs: ["ořezávátko"] },
          { en: ["row of desks"], cs: ["řada lavic", "oddělení"] },
          { en: ["rubber"], cs: ["guma"] },
          { en: ["ruler"], cs: ["pravítko"] },
          { en: ["whiteboard"], cs: ["bílá tabule"] },
        ],
      },
      {
        name: "Exams",
        words: [
          {
            name: "Exams",
            words: [
              { en: ["academic results"], cs: ["studijní výsledky"] },
              { en: ["academic standards"], cs: ["studijní požadavky"] },
              { en: ["exam paper"], cs: ["test"] },
              { en: ["past exam paper"], cs: ["test z minulých let"] },
              { en: ["exam results"], cs: ["výsledky zkoušky"] },
              { en: ["examination", "exam"], cs: ["zkoušky"] },
              {
                en: ["get a place at a university"],
                cs: ["dostat se na univerzitu"],
              },
              {
                en: ["school-leaving exam"],
                cs: ["závěrečná zkouška", "maturita"],
              },
              {
                en: ["university entrance exam"],
                cs: ["přijímací zkouška na univerzitu"],
              },
            ],
          },
          {
            name: "Useful expressions",
            words: [
              { en: ["cheat in an exam"], cs: ["podvádět při zkoušce"] },
              {
                en: ["do an exam", "sit an exam", "take an exam"],
                cs: ["skládat zkoušku"],
              },
              {
                en: ["do badly in an exam"],
                cs: ["mít špatné výsledky u zkoušky"],
              },
              {
                en: ["do well in an exam"],
                cs: ["mít dobré výsledky u zkoušky"],
              },
              { en: ["fail an exam"], cs: ["propadnout u zkoušky"] },
              {
                en: ["get 56 marks in a test", "score 56 marks in a test"],
                cs: ["dostat v testu 56 bodů"],
              },
              { en: ["grade", "mark"], cs: ["stupeň", "známka"] },
              {
                en: ["grade exam papers", "mark exam papers"],
                cs: ["známkovat zkouškové archy", "známkovat zkouškové otázky"],
              },
              { en: ["grade a test", "mark a test"], cs: ["známkovat test"] },
              {
                en: ["grade homework", "mark homework"],
                cs: ["známkovat domácí úkol"],
              },
              { en: ["pass an exam"], cs: ["složit zkoušku"] },
              {
                en: ["prepare for an exam"],
                cs: ["připravovat se na zkoušku"],
              },
              { en: ["retake an exam"], cs: ["opakovat zkoušku"] },
              { en: ["revise for an exam"], cs: ["opakovat si na zkoušku"] },
              { en: ["study for an exam"], cs: ["učit se na zkoušku"] },
            ],
          },
        ],
      },
      {
        name: "Being at school / Studying",
        words: [
          {
            name: "Being at school / Studying",
            words: [
              { en: ["absence"], cs: ["nepřítomnost"] },
              { en: ["absent"], cs: ["nepřítomen"] },
              { en: ["attendance"], cs: ["docházka"] },
              { en: ["break"], cs: ["přestávka"] },
              {
                en: ["bully"],
                cs: ["ten, kdo šikanuje", "ten, kdo ubližuje spolužákům"],
              },
              { en: ["clas"], cs: ["lekce", "vyučování"] },
              { en: ["competition"], cs: ["soutěž"] },
              { en: ["compulsory"], cs: ["povinný"] },
              { en: ["deadline"], cs: ["termín", "lhůta"] },
              { en: ["grade", "mark"], cs: ["stupeň", "známka"] },
              { en: ["grant", "scholarship"], cs: ["stipendium"] },
              { en: ["holiday"], cs: ["prázdniny"] },
              { en: ["learning difficulties"], cs: ["poruchy učení"] },
              { en: ["lesson"], cs: ["hodina", "lekce"] },
              { en: ["lunch break"], cs: ["přestávka na oběd"] },
              { en: ["newcomer"], cs: ["nový žák"] },
              { en: ["optional"], cs: ["nepovinný", "volitelný"] },
              { en: ["present"], cs: ["přítomný", "současný"] },
              { en: ["school certificate"], cs: ["vysvědčení"] },
              { en: ["school fee"], cs: ["školné"] },
              { en: ["school trip"], cs: ["školní výlet"] },
              { en: ["set books"], cs: ["školní četba"] },
              { en: ["sports club"], cs: ["sportovní klub", "sportovní tým"] },
              { en: ["staff meeting"], cs: ["pedagogická rada"] },
              { en: ["term"], cs: ["semestr", "pololetí"] },
              { en: ["timetable"], cs: ["rozvrh hodin"] },
              { en: ["written work"], cs: ["písemná práce"] },
            ],
          },
          {
            name: "Verbs",
            words: [
              { en: ["attend"], cs: ["chodit do školy"] },
              { en: ["chatter"], cs: ["povídat"] },
              { en: ["learn"], cs: ["učit se"] },
              { en: ["set"], cs: ["zadat"] },
            ],
          },
          {
            name: "Useful expressions",
            words: [
              { en: ["attend a course"], cs: ["chodit do kuzu"] },
              { en: ["attend classes"], cs: ["chodit na vyučování"] },
              { en: ["attend school"], cs: ["chodit do školy"] },
              { en: ["discuss set books"], cs: ["rezebírat povinnou četbu"] },
              { en: ["do a course"], cs: ["studovat obor"] },
              { en: ["do a project"], cs: ["dělat projekt"] },
              {
                en: ["do a task", "do an activity"],
                cs: ["dělat úkol", "zabývat se činností"],
              },
              { en: ["do an exercise"], cs: ["dělat cvičení"] },
              { en: ["do an experiment"], cs: ["provádět pokus"] },
              { en: ["do homework"], cs: ["dělat domácí úkol"] },
              { en: ["do one's best"], cs: ["pracovat co nejlépe"] },
              { en: ["go to school"], cs: ["chodit do školy"] },
              { en: ["hand in homework"], cs: ["odevzdat domácí úkol"] },
              { en: ["have a break"], cs: ["dát si pauzu"] },
              { en: ["make a presentation"], cs: ["dělat prezentace"] },
              { en: ["make mistakes"], cs: ["dělat chyby"] },
              { en: ["make notes"], cs: ["dělat si poznámky"] },
              { en: ["make progress"], cs: ["dělat pokroky"] },
              { en: ["memorise", "learn by heart"], cs: ["učit se nazpaměť"] },
              { en: ["miss lessons"], cs: ["zameškat hodiny"] },
              {
                en: ["participate", "take part in a lesson"],
                cs: ["zapojit se v hodině"],
              },
              {
                en: ["pay attention in class"],
                cs: ["dávat při vyučování pozor"],
              },
              { en: ["read maps"], cs: ["šíst z mapy"] },
              {
                en: ["set an essay"],
                cs: ["zadat písemnou práci", "zadat esej"],
              },
              { en: ["set homework"], cs: ["zadat domácí úkol"] },
              { en: ["skip classes", "play truant"], cs: ["chodit za školu"] },
              { en: ["solve a problem"], cs: ["řešit problém"] },
              { en: ["study hard"], cs: ["pilně studovat"] },
              { en: ["study sources"], cs: ["studijní prameny"] },
              { en: ["take the register"], cs: ["zapsat do třídnice"] },
              { en: ["turn up late", "be late"], cs: ["přijít pozdě"] },
              { en: ["wipe the board"], cs: ["smazat tabuli"] },
              { en: ["write an essay"], cs: ["napsat esej"] },
            ],
          },
        ],
      },
      {
        name: "Graduation",
        words: [
          {
            name: "Graduation",
            words: [
              {
                en: ["BA", "Bachlor of Arts"],
                cs: ["bakalář (humanitní obory)"],
              },
              {
                en: ["BSc", "Bachelor of Science"],
                cs: ["bakalář (přírodní vědy)"],
              },
              { en: ["graduate"], cs: ["absolvent"] },
              {
                en: ["MA", "Master of Arts"],
                cs: ["magistr (humanitní obory)"],
              },
              {
                en: ["MSc", "Master of Science"],
                cs: ["magistr (přírodní vědy)"],
              },
              { en: ["PhD", "Doctor of Philosophy"], cs: ["doktor"] },
            ],
          },
          {
            name: "Useful expressions",
            words: [
              { en: ["get into university"], cs: ["dostat se na univerzitu"] },
              {
                en: ["graduate from university"],
                cs: ["vystudovat univezitu"],
              },
              {
                en: [
                  "receive a certificate",
                  "obtain a certificate",
                  "get a certificate",
                ],
                cs: ["získat certifikát"],
              },
              {
                en: ["receive a degree", "obtain a degree", "get a degree"],
                cs: ["získat akademickou hodnost", "získat titul"],
              },
              {
                en: ["receive a diploma", "obtain a diploma", "get a diploma"],
                cs: ["získat diplom"],
              },
            ],
          },
        ],
      },
      {
        name: "Adjectives describing teachers and students",
        words: [
          { en: ["active"], cs: ["aktivní"] },
          { en: ["cooperative"], cs: ["ochotný spolupracovat"] },
          { en: ["uncooperative"], cs: ["nespolupracující"] },
          { en: ["demanding"], cs: ["náročný"] },
          { en: ["fair"], cs: ["čestný", "spravedlivý"] },
          { en: ["unfair"], cs: ["nespravedlivý"] },
          { en: ["gifted"], cs: ["nadaný"] },
          { en: ["imaginative"], cs: ["nápaditý"] },
          { en: ["motivated"], cs: ["motivovaný"] },
          { en: ["motivating"], cs: ["motivující"] },
          { en: ["passive"], cs: ["pasivní"] },
          { en: ["professional"], cs: ["profesionální"] },
          { en: ["punctual"], cs: ["přesný"] },
          { en: ["strict"], cs: ["přísný"] },
          { en: ["systematic"], cs: ["systematický"] },
          { en: ["talented"], cs: ["talentovaný"] },
        ],
      },
    ],
  },
  {
    name: "Chapter 4",
    words: [
      {
        name: "Jobs",
        words: [
          { en: ["accountant"], cs: ["účetní"] },
          { en: ["au pair"], cs: ["au pair"] },
          { en: ["babysitter"], cs: ["někdo na hlídání dětí", "chůva"] },
          { en: ["beautician"], cs: ["kosmetička"] },
          { en: ["bus driver"], cs: ["řidič autobusu"] },
          { en: ["car mechanic"], cs: ["automechanik"] },
          { en: ["chef"], cs: ["šéfkuchař"] },
          { en: ["chemist", "pharmacist"], cs: ["farmaceut"] },
          { en: ["cleaner"], cs: ["uklízečka"] },
          { en: ["computer programmer"], cs: ["programátor"] },
          { en: ["cook"], cs: ["kuchař"] },
          { en: ["dentist"], cs: ["zubař"] },
          { en: ["doctor"], cs: ["lékař"] },
          { en: ["dressmaker"], cs: ["švadlena", "dámský krejčí"] },
          { en: ["driving instructor"], cs: ["instruktor autoškoly"] },
          { en: ["economist"], cs: ["ekonom"] },
          { en: ["electrician"], cs: ["elektrikář"] },
          { en: ["engineer"], cs: ["inženýr", "technik"] },
          { en: ["executive"], cs: ["vedoucí úředník", "manažer"] },
          { en: ["farmer"], cs: ["rolník", "farmář"] },
          { en: ["fashion designer"], cs: ["módní návrhář"] },
          { en: ["film director"], cs: ["režisér"] },
          { en: ["firefighter"], cs: ["hasič"] },
          { en: ["flight attendant"], cs: ["letuška", "stevard"] },
          { en: ["fruit picker"], cs: ["česač ovoce"] },
          { en: ["hairdresser"], cs: ["kadeřník"] },
          { en: ["housewife"], cs: ["hospodyně", "žena v domácnosti"] },
          { en: ["instructor"], cs: ["instruktor"] },
          { en: ["IT specialist"], cs: ["informatik"] },
          { en: ["journalist"], cs: ["novinář"] },
          { en: ["lawyer"], cs: ["právník"] },
          { en: ["lecturer"], cs: ["lektor"] },
          { en: ["librarian"], cs: ["knihovník"] },
          {
            en: ["lollipop lady"],
            cs: [
              "žena",
              " která dohlíží na bezpečnost školáků na přechodu při cestě do školy",
            ],
          },
          {
            en: ["lollipop man"],
            cs: [
              "muž",
              " který dohlíží na bezpečnost školáků na přechodu při cestě do školy",
            ],
          },
          { en: ["manager"], cs: ["vedoucí", "manažer"] },
          { en: ["miner"], cs: ["horník"] },
          { en: ["musician"], cs: ["hudebník"] },
          { en: ["nurse"], cs: ["zdravotní sestra", "ošetřovatel"] },
          { en: ["painter"], cs: ["malíř"] },
          { en: ["photographer"], cs: ["fotograf"] },
          { en: ["pilot"], cs: ["pilot"] },
          { en: ["plumber"], cs: ["instalatér"] },
          { en: ["police officer"], cs: ["policista"] },
          { en: ["politician"], cs: ["politik"] },
          { en: ["postman"], cs: ["listonoš"] },
          { en: ["postwoman"], cs: ["listonoška"] },
          { en: ["psychologist"], cs: ["psycholog"] },
          { en: ["receptionist"], cs: ["recepční"] },
          {
            en: ["sales representative", "sales rep"],
            cs: ["obchodní zástupce"],
          },
          { en: ["scientist"], cs: ["vědec"] },
          { en: ["secretary"], cs: ["sekretář", "tajemník"] },
          { en: ["security guard"], cs: ["pracovník ochrany"] },
          { en: ["shop assistant"], cs: ["prodavač"] },
          { en: ["shopkeeper"], cs: ["majitel obchodu"] },
          { en: ["stockbroker"], cs: ["burzovní makléř"] },
          { en: ["surgeon"], cs: ["chirurg"] },
          { en: ["tailor"], cs: ["krejčí"] },
          { en: ["taxi driver"], cs: ["taxikář"] },
          { en: ["teacher"], cs: ["učitel"] },
          { en: ["ticket inspector"], cs: ["revizor", "průvodčí"] },
          { en: ["tour guide"], cs: ["průvodce"] },
          { en: ["translator"], cs: ["překladatel"] },
          { en: ["travel agent"], cs: ["pracovník cestovní kanceláře"] },
          { en: ["TV presenter"], cs: ["televizní moderátor"] },
          { en: ["vet"], cs: ["veterinář"] },
          { en: ["waiter"], cs: ["číšník"] },
          { en: ["waitress"], cs: ["servírka"] },
        ],
      },
      {
        name: "Adjectives to describe jobs",
        words: [
          { en: ["badly paid"], cs: ["špatně placený"] },
          { en: ["full-time"], cs: ["plný úvazek"] },
          { en: ["manual"], cs: ["manuální"] },
          { en: ["part-time"], cs: ["částečný úvazek"] },
          { en: ["permanent"], cs: ["stálý", "trvalý"] },
          { en: ["temporary"], cs: ["dočasný"] },
          { en: ["well-paid"], cs: ["dobře placený"] },
        ],
      },
      {
        name: "Looking for a job",
        words: [
          {
            name: "Looking for a job",
            words: [
              { en: ["applicant"], cs: ["uchazeč o práci"] },
              { en: ["candidate"], cs: ["kandidát"] },
              { en: ["suitable candidate"], cs: ["vhodný kandidát"] },
              { en: ["curriculum viae", "CV"], cs: ["životopis"] },
              { en: ["employment contract"], cs: ["pracovní smlouva"] },
              { en: ["experience"], cs: ["zkušenost"] },
              { en: ["five years' experience"], cs: ["pětiletá zkušenost"] },
              { en: ["form"], cs: ["formulář"] },
              { en: ["application form"], cs: ["formulář žádosti o práci"] },
              { en: ["job"], cs: ["práce"] },
              { en: ["job advertisement"], cs: ["pracovní inzerát"] },
              { en: ["job application"], cs: ["žádost o práci"] },
              { en: ["job centre"], cs: ["pracovní úřad"] },
              { en: ["job interview"], cs: ["pracovní pohovor"] },
              { en: ["opportunity"], cs: ["příležitost"] },
              { en: ["previous experience"], cs: ["předchozí zkušenost"] },
              { en: ["qualifications"], cs: ["kvalifikace"] },
              { en: ["recruitment"], cs: ["nábor"] },
              { en: ["references"], cs: ["doporučení", "reference"] },
              { en: ["skills"], cs: ["dovednosti", "znalosti"] },
              { en: ["computer skills"], cs: ["znalost práce s počítačem"] },
              { en: ["training"], cs: ["školení"] },
              { en: ["training session"], cs: ["pracovní školení", "trénink"] },
              { en: ["vacancy"], cs: ["volné místo"] },
            ],
          },
          {
            name: "Verbs",
            words: [{ en: ["recruit"], cs: ["nabírat"] }],
          },
          {
            name: "Useful expressions",
            words: [
              { en: ["apply for a job"], cs: ["žádat o práci"] },
              { en: ["apply for a position"], cs: ["ucházet o pozici"] },
              { en: ["enclose a CV"], cs: ["přiložit životopis"] },
              { en: ["fill in a form"], cs: ["vyplnit formulář"] },
              { en: ["find work"], cs: ["najít práci"] },
              {
                en: ["interview applicants"],
                cs: ["vést pracovní pohovor s uchazeči"],
              },
              { en: ["look for a job"], cs: ["hledat práci"] },
              {
                en: ["the job involves dealing with people"],
                cs: ["součástí práce je jednání s lidmi"],
              },
            ],
          },
        ],
      },
      {
        name: "Work and money",
        words: [
          {
            name: "Work and money",
            words: [
              { en: ["bonus"], cs: ["prémie", "bonus"] },
              { en: ["earnings"], cs: ["výdělky"] },
              { en: ["fee"], cs: ["poplatky"] },
              {
                en: ["fringe benefits", "perks"],
                cs: ["vedlejší výhody", "benefity (mimo plat)"],
              },
              { en: ["income"], cs: ["příjem"] },
              { en: ["minimum wage"], cs: ["minimální mzda"] },
              { en: ["pay", "salary"], cs: ["plat"] },
              { en: ["decent pay"], cs: ["slušný plat"] },
              { en: ["pay rise"], cs: ["zvýšení platu"] },
              { en: ["reasonable pay"], cs: ["přiměřený plat"] },
              { en: ["sick pay"], cs: ["nemocenská"] },
              { en: ["pension"], cs: ["penze", "důchod"] },
              { en: ["profit"], cs: ["zisk"] },
              { en: ["starting salary"], cs: ["nástupní plat"] },
              {
                en: ["wages"],
                cs: [
                  "mzda (týdenní",
                  " denní",
                  " hodinová",
                  " většinou za nekvalifikovanou práci)",
                ],
              },
            ],
          },
          {
            name: "Verbs",
            words: [
              { en: ["earn"], cs: ["vydělávat"] },
              { en: ["pay"], cs: ["platit"] },
            ],
          },
          {
            name: "Useful expressions",
            words: [
              { en: ["get a pay rise"], cs: ["dostat přidáno"] },
              { en: ["get paid overtime"], cs: ["dostat zaplacené presčasy"] },
            ],
          },
        ],
      },
      {
        name: "At work",
        words: [
          {
            name: "At work",
            words: [
              { en: ["at work"], cs: ["v práci"] },
              { en: ["career prospects"], cs: ["kariérní vyhlídky"] },
              { en: ["deadline"], cs: ["termín dokončení práce"] },
              { en: ["hard work"], cs: ["težká práce"] },
              { en: ["management"], cs: ["vedení"] },
              { en: ["office"], cs: ["kancelář"] },
              { en: ["overwork"], cs: ["přepracování"] },
              {
                en: ["responsible for somebody", "responsible for something"],
                cs: ["zodpovídat za něco", "zodpovídat za někoho"],
              },
              { en: ["teamwork"], cs: ["týmová práce"] },
              { en: ["working conditions"], cs: ["pracovní podmínky"] },
              { en: ["workplace"], cs: ["pracoviště"] },
            ],
          },
          {
            name: "Verbs",
            words: [
              {
                en: ["assist somebody"],
                cs: ["pomáhat někomu", "asistovat někomu"],
              },
              { en: ["manage"], cs: ["řídit", "zvládat"] },
              { en: ["work"], cs: ["pracovat"] },
            ],
          },
          {
            name: "Useful expressions",
            words: [
              {
                en: ["be in charge of something"],
                cs: ["mít na starost", "zodpovídat za něco"],
              },
              { en: ["be part of a team"], cs: ["být součástí týmu"] },
              { en: ["be self-employed"], cs: ["samostatně podnikat"] },
              { en: ["be promoted", "get promoted"], cs: ["povýšit"] },
              {
                en: ["clock in", "clock on"],
                cs: ["píchnout příchod do práce"],
              },
              { en: ["concentrate on something"], cs: ["soustředit se na"] },
              { en: ["deal with people"], cs: ["jednat s lidmi"] },
              { en: ["do a hard day's work"], cs: ["pracovat těžce celý den"] },
              { en: ["do a training course"], cs: ["účastnit se školení"] },
              { en: ["do one's job well"], cs: ["dělat svou práci dobře"] },
              { en: ["do physical work"], cs: ["pracovat manuálně"] },
              {
                en: ["do something for a living", "earn a living"],
                cs: ["vydělávat si na živobytí"],
              },
              {
                en: ["do overtime", "work overtime"],
                cs: ["pracovat přesčas"],
              },
              { en: ["get a job"], cs: ["dostat práci"] },
              { en: ["give somebody a hand"], cs: ["pomáhat někomu"] },
              { en: ["go on strike"], cs: ["stávkovat"] },
              { en: ["go to work"], cs: ["jít do práce"] },
              { en: ["pay per hour"], cs: ["platit hodinově"] },
              { en: ["pay per month"], cs: ["platit měsíčně"] },
              { en: ["pay per week"], cs: ["platit týdně"] },
              { en: ["run a business"], cs: ["provozovat podnik"] },
              {
                en: ["take over duties from somebody"],
                cs: ["převzít od někoho povinnosti"],
              },
              { en: ["work as an engineer"], cs: ["pracovat jako inženýr"] },
              { en: ["work for a company"], cs: ["pracovat pro podnik"] },
              { en: ["work from home"], cs: ["pracovat doma"] },
              { en: ["work long hours"], cs: ["pracovat dlouho"] },
              { en: ["work on something"], cs: ["pracovat na něčem"] },
              { en: ["work shifts"], cs: ["pracovat na směny"] },
            ],
          },
        ],
      },
      {
        name: "Holidays and days off",
        words: [
          {
            name: "Holidays and days off",
            words: [
              { en: ["holiday"], cs: ["dovolená", "svátek"] },
              { en: ["leave"], cs: ["dovolená"] },
              { en: ["maternity leave"], cs: ["mateřská dovolená"] },
              { en: ["paid leave"], cs: ["placená dovolená"] },
              { en: ["sick leave"], cs: ["pracovní neschopnost"] },
            ],
          },
          {
            name: "Useful expressions",
            words: [
              { en: ["be off sick"], cs: ["být na neschopence"] },
              {
                en: ["take a week's leave"],
                cs: ["vzít si týdenní dovolenou"],
              },
              { en: ["take a day off work"], cs: ["vzít si den volna"] },
            ],
          },
        ],
      },
      {
        name: "People at work",
        words: [
          { en: ["boss"], cs: ["šéf"] },
          { en: ["colleague", "workmate"], cs: ["kolega", "spolupracovník"] },
          { en: ["employee"], cs: ["zaměstnanec"] },
          { en: ["employer"], cs: ["zaměstnavatel"] },
          { en: ["staff"], cs: ["zaměstnanci"] },
          { en: ["team"], cs: ["skupina", "tým"] },
          { en: ["worker"], cs: ["dělník"] },
        ],
      },
      {
        name: "Employment",
        words: [
          { en: ["career"], cs: ["profesní kariéra"] },
          { en: ["employ"], cs: ["zaměstnat"] },
          { en: ["employment"], cs: ["zaměstnání"] },
          { en: ["job"], cs: ["práce"] },
          { en: ["current job"], cs: ["běžná práce"] },
          { en: ["holiday job"], cs: ["prázdninová brigáda"] },
          { en: ["summer job"], cs: ["letní brigáda"] },
          { en: ["odd jobs"], cs: ["příležitostné práce"] },
          { en: ["occupation"], cs: ["zaměstnání", "povolání"] },
          { en: ["position", "post"], cs: ["pracovní pozice", "postavení"] },
          {
            en: ["profession"],
            cs: ["profese (zaměstnání s odbornou kvalifikací)"],
          },
          { en: ["by profession"], cs: ["zaměstnáním"] },
          { en: ["self-employed"], cs: ["samostatně podnikající"] },
          { en: ["work experience"], cs: ["pracovní zkušenosti"] },
        ],
      },
      {
        name: "Lack of employment",
        words: [
          {
            name: "Lack of employment",
            words: [
              { en: ["economic crisis"], cs: ["hospodářská krize"] },
              { en: ["pensioner"], cs: ["důchodce"] },
              { en: ["retirement"], cs: ["důchod", "penze"] },
              { en: ["unemployed", "out of work"], cs: ["nezaměstnaný"] },
              { en: ["unemployment"], cs: ["nezaměstnanost"] },
              { en: ["high unemployment"], cs: ["vysoká nezaměstnanost"] },
              { en: ["low unemployment"], cs: ["nízká nezaměstnanost"] },
              {
                en: ["unemployment benefit"],
                cs: ["dávka v nezaměsatnanosti"],
              },
            ],
          },
          {
            name: "Verbs",
            words: [
              { en: ["resign"], cs: ["vzdát se funkce", "odstoupit"] },
              { en: ["retire"], cs: ["jít do důchodu"] },
            ],
          },
          {
            name: "Useful expressions",
            words: [
              {
                en: [
                  "fire somebody",
                  "sack somebody",
                  "give somebody the sack",
                ],
                cs: ["propustit", "vyhodit někoho z práce"],
              },
              {
                en: ["give up", "quit one's job"],
                cs: ["odejít", "skončit s prací"],
              },
              { en: ["go bankrupt"], cs: ["zbankrotovat"] },
              {
                en: ["hand in one's resignation"],
                cs: ["podat rezignaci", "dát výpověď"],
              },
              { en: ["lose one's job"], cs: ["přijít o práci"] },
              {
                en: ["make somebody redundant"],
                cs: ["propustit někoho pro nadbytečnost"],
              },
              { en: ["on the dole"], cs: ["být na podpoře"] },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Chapter 5",
    words: [
      { en: ["adopted child"], cs: ["adoptované dítě"] },
      { en: ["adoption"], cs: ["adopce"] },
      { en: ["aunt"], cs: ["teta"] },
      { en: ["brother"], cs: ["bratr"] },
      { en: ["brother-in-law"], cs: ["švagr"] },
      { en: ["child"], cs: ["dítě"] },
      { en: ["children"], cs: ["děti"] },
      { en: ["cousin"], cs: ["bratranec", "sestřenice"] },
      { en: ["daughter"], cs: ["dcera"] },
      { en: ["daughter-in-law"], cs: ["snacha"] },
      { en: ["ex-husband"], cs: ["bývalý manžel"] },
      { en: ["ex-wife"], cs: ["bývalá manželka"] },
      { en: ["family member"], cs: ["člen rodiny"] },
      { en: ["family tree"], cs: ["rodokmen"] },
      { en: ["father"], cs: ["otec"] },
      { en: ["father-in-law"], cs: ["tchán"] },
      { en: ["foster children"], cs: ["dítě svěřené do opatrovnické péče"] },
      { en: ["foster parents"], cs: ["pěstouni"] },
      { en: ["grandchildren"], cs: ["vnuci"] },
      { en: ["granddaughter"], cs: ["vnučka"] },
      { en: ["grandfather"], cs: ["dědeček"] },
      { en: ["grandmother"], cs: ["babička"] },
      { en: ["grandparents"], cs: ["prarodiče"] },
      { en: ["grandson"], cs: ["vnuk"] },
      { en: ["great-grandchildren"], cs: ["pravnuci"] },
      { en: ["great-granddaughter"], cs: ["pravnučka"] },
      { en: ["great-grandmother"], cs: ["prababička"] },
      { en: ["great-grandparents"], cs: ["prarodiče"] },
      { en: ["great-grandson"], cs: ["pravnuk"] },
      { en: ["half-brother"], cs: ["nevlastní bratr"] },
      { en: ["half-sister"], cs: ["nevlastní sestra"] },
      { en: ["husband"], cs: ["manžel"] },
      { en: ["mother"], cs: ["matka"] },
      { en: ["mother-in-law"], cs: ["tchyně"] },
      { en: ["nephew"], cs: ["synovec"] },
      { en: ["niece"], cs: ["neteř"] },
      { en: ["only child"], cs: ["jedináček"] },
      { en: ["orphan"], cs: ["sirotek"] },
      { en: ["parents"], cs: ["rodiče"] },
      { en: ["relative"], cs: ["příbuzný"] },
      { en: ["siblings"], cs: ["sourozenci"] },
      { en: ["sister"], cs: ["sestra"] },
      { en: ["sister-in-law"], cs: ["švagrová"] },
      { en: ["son"], cs: ["syn"] },
      { en: ["son-in-law"], cs: ["zeť"] },
      {
        en: ["stepbrother"],
        cs: ["nevlastní bratr (syn otčíma nebo nevlastní matky)"],
      },
      { en: ["stepdaughter"], cs: ["nevlastní dcera"] },
      { en: ["stepfather"], cs: ["otčím"] },
      { en: ["stepmother"], cs: ["nevlastní matka"] },
      {
        en: ["stepsister"],
        cs: ["nevlastní dcera (dcera otčíma nebo nevlastní matky)"],
      },
      { en: ["stepson"], cs: ["nevlastní syn"] },
      { en: ["twins"], cs: ["dvojčata"] },
      { en: ["uncle"], cs: ["strýc"] },
      { en: ["wife"], cs: ["manželka"] },
      { en: ["anniversary"], cs: ["výročí"] },
      { en: ["birthday"], cs: ["narozeniny"] },
      { en: ["birthday cake"], cs: ["narozeninoý dort"] },
      { en: ["birthday present"], cs: ["dárek k narozenínám"] },
      { en: ["Christmas"], cs: ["Vánoce"] },
      { en: ["Christmas card"], cs: ["vánoční přání", "pohlednice"] },
      { en: ["Christmas Eve"], cs: ["Štědrý den"] },
      { en: ["Easter"], cs: ["Velikonoce"] },
      { en: ["family gathering"], cs: ["rodinné setkání"] },
      { en: ["Father's Day"], cs: ["Den otců"] },
      { en: ["festival"], cs: ["svátek", "festival"] },
      { en: ["funeral"], cs: ["pohřeb"] },
      { en: ["Mother's Day"], cs: ["Den matek"] },
      { en: ["New Year's Day"], cs: ["Nový Rok"] },
      { en: ["New Year's Eve"], cs: ["Silvestr"] },
      { en: ["wedding"], cs: ["svatba"] },
      { en: ["wedding reception"], cs: ["svatební hostina"] },
      { en: ["blow out candles"], cs: ["sfouknout svíčky"] },
      { en: ["celebrate somebody's birthday"], cs: ["slavit něčí narozeniny"] },
      { en: ["decorate the Christmas tree"], cs: ["zdobit vánoční stromek"] },
      { en: ["dress up as"], cs: ["převléci se za"] },
      { en: ["celebrate, have a celebration"], cs: ["slavit"] },
      { en: ["paint eggs"], cs: ["malovat vajíčka"] },
      { en: ["divorced"], cs: ["rozvedený", "rozvedená"] },
      { en: ["engaged"], cs: ["zasnoubený", "zasnoubená"] },
      { en: ["engagement ring"], cs: ["zásnubní prsten"] },
      { en: ["honeymoon"], cs: ["líbánky"] },
      { en: ["marriage"], cs: ["manželství"] },
      { en: ["married"], cs: ["ženatý", "vdaná"] },
      { en: ["married couple"], cs: ["manželský pár"] },
      { en: ["pregnant"], cs: ["těhotná"] },
      { en: ["single"], cs: ["svobodný"] },
      {
        en: ["single father"],
        cs: ["otec, který sám vyhovává dítě", "samoživitel"],
      },
      {
        en: ["single mother"],
        cs: ["matka, která sama vychovává dítě", "samoživitelka"],
      },
      { en: ["be expecting a child"], cs: ["očekávat narození dítěte"] },
      { en: ["become", "get engaged"], cs: ["zasnoubit"] },
      { en: ["bring up", "rasi children"], cs: ["vychovávat děti"] },
      {
        en: ["get married to somebody", "marry somebody"],
        cs: ["oženit se", "vdát se"],
      },
      {
        en: ["look after children", "take care of children"],
        cs: ["starat se o děti"],
      },
      { en: ["run away from home"], cs: ["utéct z domova"] },
      { en: ["entertainment"], cs: ["zábava"] },
      { en: ["free time"], cs: ["volný čas"] },
      { en: ["leisure activities"], cs: ["činnosti ve volném čase", "záliby"] },
      { en: ["weekend plans"], cs: ["plány na víkend"] },
      { en: ["dance"], cs: ["tančit"] },
      { en: ["play"], cs: ["hrát"] },
      { en: ["ask somebody out"], cs: ["pozvat někoho na schůzku"] },
      { en: ["dress up"], cs: ["elegantně se obléci", "vystrojit se"] },
      { en: ["go bowling"], cs: ["jít na bowling"] },
      { en: ["go clubbing"], cs: ["jít do klubů"] },
      { en: ["go dancing"], cs: ["jít si zatancovat"] },
      { en: ["go for a walk"], cs: ["jít na procházku"] },
      { en: ["go out"], cs: ["jít ven"] },
      { en: ["go out for a meal"], cs: ["jít do restaurace"] },
      { en: ["go swimming"], cs: ["jít si zaplavat"] },
      { en: ["go to a concert"], cs: ["jít na koncert"] },
      { en: ["go to a disco"], cs: ["jít na diskotéku"] },
      { en: ["go to a party"], cs: ["jít na večírek"] },
      { en: ["go to the cinema"], cs: ["jít do kina"] },
      { en: ["have a party"], cs: ["uspořádat večírek"] },
      {
        en: ["listen to music", "listen to the radio"],
        cs: ["poslouchat hudbu", "poslouchat rádio"],
      },
      { en: ["look forward to something"], cs: ["těšit se na něco"] },
      { en: ["meet friends"], cs: ["scházet se s přáteli"] },
      { en: ["pass time"], cs: ["trávit čas"] },
      { en: ["play board games"], cs: ["hrát deskové hry"] },
      { en: ["play cards"], cs: ["hrát karty"] },
      { en: ["play chess"], cs: ["hrát šachy"] },
      { en: ["play computer games"], cs: ["hrát počítačové hry"] },
      { en: ["play the guitar"], cs: ["hrát na kytaru"] },
      { en: ["play the piano"], cs: ["hrát na piano"] },
      { en: ["play video games"], cs: ["hrát videohry"] },
      {
        en: ["read books", "read comics", "read magazines"],
        cs: ["číst knížky", "číst komiksy", "číst časopisy"],
      },
      { en: ["spend time outdoors"], cs: ["trávit čas venku"] },
      {
        en: ["wath a film", "watch a video", "watch TV"],
        cs: ["dívat se na film", "dívat se na video", "dívat se na televizi"],
      },
      { en: ["babysit"], cs: ["hlídat děti"] },
      { en: ["lie"], cs: ["ležet"] },
      { en: ["daily routine"], cs: ["denní režim"] },
      { en: ["eat out"], cs: ["jíst v restauraci"] },
      { en: ["get dressed"], cs: ["obléci se"] },
      { en: ["get ready"], cs: ["chystat se", "připravovat se"] },
      { en: ["get up"], cs: ["vstávat"] },
      {
        en: ["go to bed early", "go to bed late"],
        cs: ["jít brzy spát", "jít pozdě spát"],
      },
      { en: ["go to school"], cs: ["jít do školy"] },
      { en: ["go to work"], cs: ["jít do práce"] },
      { en: ["have a meal"], cs: ["jíst", "dát si jídlo"] },
      { en: ["have breakfast"], cs: ["dát si snídani"] },
      { en: ["have dinner"], cs: ["dát si oběd", "dát si večeři"] },
      { en: ["have lunch"], cs: ["dát si oběd"] },
      { en: ["have supper"], cs: ["dát si lehkou večeři"] },
      { en: ["have tea"], cs: ["dát si svačinu"] },
      { en: ["have a bath", "take a bath"], cs: ["vykoupat se"] },
      { en: ["have a rest", "take a rest"], cs: ["odpočinout si"] },
      { en: ["have a shower", "take a shower"], cs: ["dát si sprchu"] },
      { en: ["lie down"], cs: ["lehnout si"] },
      { en: ["lie in"], cs: ["přispat si"] },
      { en: ["make one's bed"], cs: ["ustlat si postel"] },
      { en: ["prepare a meal"], cs: ["připravit jídlo"] },
      { en: ["sweep the floor"], cs: ["zamést podlahu"] },
      { en: ["take a nap"], cs: ["zdřímnout si"] },
      { en: ["take the children to school"], cs: ["dovést děti do školy"] },
      { en: ["take the dog for a walk"], cs: ["vzít psa na procházku"] },
      {
        en: ["take turns to do something"],
        cs: ["střídat se v", "střídat se při"],
      },
      { en: ["tidy up one's room"], cs: ["uklidit si pokoj"] },
      { en: ["wake up"], cs: ["probudit se"] },
      { en: ["adolescence"], cs: ["dospívání", "adolescence"] },
      { en: ["adolescent"], cs: ["dospívající", "adolescent"] },
      { en: ["adult"], cs: ["dospělí"] },
      { en: ["adulthood"], cs: ["dospělost"] },
      { en: ["age group"], cs: ["věková skupina"] },
      { en: ["at the age of"], cs: ["ve věku"] },
      { en: ["birth"], cs: ["narození"] },
      { en: ["childhood"], cs: ["dětství"] },
      { en: ["dead"], cs: ["mrtvý"] },
      { en: ["death"], cs: ["smrt"] },
      { en: ["generation"], cs: ["generace"] },
      { en: ["grown-up"], cs: ["dospělý"] },
      { en: ["middle age"], cs: ["střední věk"] },
      { en: ["middle-aged"], cs: ["ve středním věku"] },
      { en: ["old age"], cs: ["stáři"] },
      { en: ["youth"], cs: ["mládí"] },
      { en: ["die"], cs: ["zemřít"] },
      { en: ["be born"], cs: ["narodit se"] },
      { en: ["give birth to a child", "have a baby"], cs: ["porodit dítě"] },
      { en: ["grow up"], cs: ["vyrůst"] },
      { en: ["boyfriend"], cs: ["přítel"] },
      { en: ["close friend"], cs: ["blízký přítel"] },
      { en: ["fiancé"], cs: ["snoubenec"] },
      { en: ["fiancée"], cs: ["snoubenka"] },
      { en: ["girlfriend"], cs: ["přítelkyně"] },
      { en: ["lovebirds"], cs: ["zamilovaní"] },
      { en: ["be attracked to somebody"], cs: ["cítit náklonnost k někomu"] },
      {
        en: ["break up", "split up with somebody"],
        cs: ["rozejít se s někým"],
      },
      {
        en: ["end a relationship with somebody"],
        cs: ["ukončit s někým vztah"],
      },
      {
        en: ["enjoy oneself", "have fun", "have a good time"],
        cs: ["dobře se bavit"],
      },
      {
        en: ["fall out", "have a row", "have an argument"],
        cs: ["pohádat se"],
      },
      { en: ["get divorced"], cs: ["rozvést se"] },
      { en: ["get on well with somebody"], cs: ["dobře s někým vycházet"] },
      { en: ["go out with somebody"], cs: ["chodit s někým"] },
      {
        en: ["have a bad relationship with somebody"],
        cs: ["mít s někým špatné vztahy"],
      },
      { en: ["have an argument"], cs: ["have a row"] },
      { en: ["make up with somebody"], cs: ["usmířit se s někým"] },
      {
        en: ["start a relationship with somebody"],
        cs: ["navázat s někým vztah"],
      },
    ],
  },
  {
    name: "Chapter 6",
    words: [
      { en: ['break'], cs: ['chléb'] },
      { en: ['brown bread'], cs: ['tmavý chléb'] },
      { en: ['white bread'], cs: ['světlý chléb'] },
      { en: ['wholemeal bread'], cs: ['celozrnný chléb'] },
      { en: ['breakfast cereal'], cs: ['cereálie', 'vločky k snídani'] },
      { en: ['cereal products'], cs: ['výrobky z obilovin'] },
      { en: ['cornflakes'], cs: ['kukuřičné lupínky'] },
      { en: ['muesli'], cs: ['müsli'] },
      { en: ['noodles', 'pasta'], cs: ['nudle', 'těstoviny'] },
      { en: ['rice'], cs: ['rýže'] },
      { en: ['roll'], cs: ['rohlík'] },
      { en: ['toast'], cs: ['topinka', 'toast'] },
      { en: ['butter'], cs: ['máslo'] },
      { en: ['cheese'], cs: ['sýr'] },
      { en: ['blue cheese'], cs: ['plísňový sýr'] },
      { en: ['cottage cheese'], cs: ['cottage', 'tvarohový sýr'] },
      { en: ['grated cheese'], cs: ['strouhaný sýr'] },
      { en: ['Parmesan cheese'], cs: ['parmezán'] },
      { en: ['dairy products'], cs: ['mléčné výrobky'] },
      { en: ['egg'], cs: ['vejce'] },
      { en: ['margarine'], cs: ['margarín'] },
      { en: ['milkshake'], cs: ['mléčný koktejl'] },
      { en: ['yoghurt'], cs: ['jogurt'] },
      { en: ['bacon'], cs: ['slanina'] },
      { en: ['beef'], cs: ['hovězí'] },
      { en: ['chicken'], cs: ['kuřecí'] },
      { en: ['ham'], cs: ['šunka'] },
      { en: ['meat'], cs: ['maso'] },
      { en: ['pork'], cs: ['vepřové'] },
      { en: ['sausage'], cs: ['párek', 'klobása'] },
      { en: ['turkey'], cs: ['krocan'] },
      { en: ['cod'], cs: ['treska'] },
      { en: ['fillet'], cs: ['filé'] },
      { en: ['fish'], cs: ['ryba', 'ryby'] },
      { en: ['herring'], cs: ['sleď'] },
      { en: ['salmon'], cs: ['losos'] },
      { en: ['sardine'], cs: ['sardinka'] },
      { en: ['seafood'], cs: ['mořské plody'] },
      { en: ['shellfish'], cs: ['jedlý korýš'] },
      { en: ['tuna'], cs: ['tuňák'] },
      { en: ['apple'], cs: ['jablko'] },
      { en: ['apricot'], cs: ['meruňka'] },
      { en: ['avocado'], cs: ['avokádo'] },
      { en: ['banana'], cs: ['banán'] },
      { en: ['blackcurrant'], cs: ['černý rybíz'] },
      { en: ['bleuberry'], cs: ['borůvka'] },
      { en: ['cherry'], cs: ['třešně', 'višně'] },
      { en: ['coconut'], cs: ['kokos'] },
      { en: ['fruit'], cs: ['ovoce'] },
      { en: ['grapefruit'], cs: ['grep'] },
      { en: ['grapes'], cs: ['hroznové víno'] },
      { en: ['kiwi fruit'], cs: ['kiwi'] },
      { en: ['lemon'], cs: ['citron'] },
      { en: ['lime'], cs: ['limetka'] },
      { en: ['mango'], cs: ['mango'] },
      { en: ['melon'], cs: ['meloun'] },
      { en: ['orange'], cs: ['pomeranč'] },
      { en: ['peach'], cs: ['broskev'] },
      { en: ['pear'], cs: ['hruška'] },
      { en: ['pineapple'], cs: ['ananas'] },
      { en: ['plum'], cs: ['švestka'] },
      { en: ['strawberry'], cs: ['jahoda'] },
      { en: ['watermelon'], cs: ['vodní meloun'] },
      { en: ['anchovy'], cs: ['ančovička'] },
      { en: ['asparagus'], cs: ['chřest'] },
      { en: ['aubergine'], cs: ['baklažán'] },
      { en: ['beans'], cs: ['fazole'] },
      { en: ['broccoli'], cs: ['brokolice'] },
      { en: ['cabbage'], cs: ['kapusta', 'zelí'] },
      { en: ['carrot'], cs: ['mrkev'] },
      { en: ['cauliflower'], cs: ['květák'] },
      { en: ['calery'], cs: ['celer'] },
      { en: ['cocumber'], cs: ['okurka'] },
      { en: ['garlic'], cs: ['česnek'] },
      { en: ['green peas'], cs: ['hrášek'] },
      { en: ['lettuce'], cs: ['hlávkový salát'] },
      { en: ['maize'], cs: ['kukuřice'] },
      { en: ['mushroom'], cs: ['houba'] },
      { en: ['onion'], cs: ['cibule'] },
      { en: ['parsley'], cs: ['petržel'] },
      { en: ['pepper'], cs: ['paprika'] },
      { en: ['green pepper'], cs: ['zelená paprika'] },
      { en: ['red pepper'], cs: ['červená paprika'] },
      { en: ['potato'], cs: ['brambora'] },
      { en: ['radish'], cs: ['ředkvička'] },
      { en: ['spinach'], cs: ['špenát'] },
      { en: ['sweetcorn'], cs: ['sladká kukuřice'] },
      { en: ['tomato'], cs: ['rajče'] },
      { en: ['vegetable'], cs: ['zelenina'] },
      { en: ['apple pie'], cs: ['jablečný koláč'] },
      { en: ['biscuit', 'cookie'], cs: ['sušenka'] },
      { en: ['cake'], cs: ['koláč', 'dort'] },
      { en: ['cheesecake'], cs: ['cheesecake', 'tvarohový koláč'] },
      { en: ['chocolate'], cs: ['čokoláda'] },
      { en: ['crisps'], cs: ['čipsy', 'lupínky'] },
      { en: ['dessert'], cs: ['moučník'] },
      { en: ['fruitcake'], cs: ['ovocný koláč', 'biskupský chlebíček'] },
      { en: ['honey'], cs: ['med'] },
      { en: ['pudding'], cs: ['moučník', 'nákyp'] },
      { en: ['sweets'], cs: ['sladkosti', 'cukroví'] },
      { en: ['fat'], cs: ['tuk'] },
      { en: ['herbs'], cs: ['bylinky'] },
      { en: ['ketchup'], cs: ['kečup'] },
      { en: ['mayonnaise'], cs: ['majonéza'] },
      { en: ['mustard'], cs: ['hořčice'] },
      { en: ['olive oil'], cs: ['olivový olej'] },
      { en: ['pepper'], cs: ['pepř'] },
      { en: ['black pepper'], cs: ['černý pepř'] },
      { en: ['salad dressing'], cs: ['zálivka', 'dressing'] },
      { en: ['salt'], cs: ['sůl'] },
      { en: ['a pinch of salt'], cs: ['špetka soli'] },
      { en: ['spice'], cs: ['koření'] },
      { en: ['sugar'], cs: ['cukr'] },
      { en: ['tomato sauce'], cs: ['rajčatová omáčka'] },
      { en: ['vinegar'], cs: ['ocet'] },
      { en: ['beer'], cs: ['pivo'] },
      { en: ['cocoa'], cs: ['kakao'] },
      { en: ['coffee'], cs: ['káva'] },
      { en: ['cola'], cs: ['cola'] },
      { en: ['drink'], cs: ['nápoj'] },
      { en: ['fizzy'], cs: ['šumivý nápoj'] },
      { en: ['soft'], cs: ['nealkoholický nápoj'] },
      { en: ['juice'], cs: ['šťáva'] },
      { en: ['tea'], cs: ['čaj'] },
      { en: ['water'], cs: ['voda'] },
      { en: ['wine'], cs: ['víno'] },
      { en: ['baked beans'], cs: ['fazole v rajské omáčce'] },
      { en: ['fish and chips'], cs: ['ryba s hranolky'] },
      { en: ['mashed potatoes'], cs: ['bramborová kaše'] },
      { en: ['omelette'], cs: ['omeleta'] },
      { en: ['pancake'], cs: ['palačinka', 'lívanec'] },
      { en: ['salad'], cs: ['salát'] },
      { en: ['steak'], cs: ['steak', 'biftek', 'řízek'] },
      { en: ['tortilla'], cs: ['tortilla'] },
      { en: ['crunchy'], cs: ['křupavý'] },
      { en: ['delicious'], cs: ['vynikající', 'lahodný'] },
      { en: ['dry'], cs: ['suchý'] },
      { en: ['fatty'], cs: ['tučný'] },
      { en: ['fresh'], cs: ['čerstvý'] },
      { en: ['hot'], cs: ['ostrý', 'pálivý'] },
      { en: ['medium'], cs: ['středně propečený'] },
      { en: ['mild'], cs: ['jemný'] },
      { en: ['rare'], cs: ['polosyrový', 'krvavý'] },
      { en: ['smelly'], cs: ['páchnoucí'] },
      { en: ['sour'], cs: ['kyselý'] },
      { en: ['sparkling'], cs: ['perlivý', 'šumivý'] },
      { en: ['spicy'], cs: ['pikantní', 'kořeněný'] },
      { en: ['stale'], cs: ['okoralý'] },
      { en: ['still'], cs: ['nesycený', 'bez bublinek'] },
      { en: ['strong'], cs: ['silný', 'výrazný'] },
      { en: ['sweet'], cs: ['sladký'] },
      { en: ['tasty'], cs: ['chutný'] },
      { en: ['weak'], cs: ['slabý'] },
      { en: ['well-done'], cs: ['dobře propečený'] },
      { en: ['yummy'], cs: ['chutný'] },
      { en: ['bag'], cs: ['sáček'] },
      { en: ['bar'], cs: ['tyčinka', 'tabulka'] },
      { en: ['bottle'], cs: ['lahev'] },
      { en: ['box'], cs: ['krabice'] },
      { en: ['can'], cs: ['plechovka'] },
      { en: ['carton'], cs: ['papírová kravice', 'karton'] },
      { en: ['glass'], cs: ['sklenička'] },
      { en: ['jar'], cs: ['sklenice'] },
      { en: ['loaf'], cs: ['bochník'] },
      { en: ['packet'], cs: ['balíček'] },
      { en: ['bowl'], cs: ['miska'] },
      { en: ['finely chopped'], cs: ['nadrobno nasekaný'] },
      { en: ['fork'], cs: ['vidlička'] },
      { en: ['frying pan'], cs: ['pánev'] },
      { en: ['ingredient'], cs: ['přísada'] },
      { en: ['kettle'], cs: ['konvice'] },
      { en: ['knife'], cs: ['nůž'] },
      { en: ['leftovers'], cs: ['zbytky jídla'] },
      { en: ['oven'], cs: ['trouba'] },
      { en: ['pan'], cs: ['rendlík', 'kastrol'] },
      { en: ['pot'], cs: ['hrnec'] },
      { en: ['recipe'], cs: ['recept'] },
      { en: ['saucepan'], cs: ['rendlík'] },
      { en: ['slice'], cs: ['plátek'] },
      { en: ['spoon'], cs: ['lžíce'] },
      { en: ['spoonful'], cs: ['plná lžička', 'lžíce'] },
      { en: ['tablespoonful'], cs: ['polévková lžíce'] },
      { en: ['add'], cs: ['přidat'] },
      { en: ['bake'], cs: ['péct'] },
      { en: ['barbecue'], cs: ['grilovat'] },
      { en: ['beat'], cs: ['šlehat'] },
      { en: ['boil'], cs: ['vařit', 'přivést k varu'] },
      { en: ['cook'], cs: ['vařit', 'připravovat'] },
      { en: ['cut'], cs: ['krájet'] },
      { en: ['freeze'], cs: ['zmrazit'] },
      { en: ['fry'], cs: ['smažit'] },
      { en: ['grate'], cs: ['nastrouhat'] },
      { en: ['grill'], cs: ['grilovat', 'připravovat na grilu'] },
      { en: ['heat'], cs: ['ohřát'] },
      { en: ['melt'], cs: ['rozpustit'] },
      { en: ['mix'], cs: ['smíchat', 'mísit'] },
      { en: ['peel'], cs: ['oloupat'] },
      { en: ['pour'], cs: ['nalít'] },
      { en: ['rise'], cs: ['kynout'] },
      { en: ['roast'], cs: ['péci'] },
      { en: ['season'], cs: ['okořenit', 'ochutit'] },
      { en: ['slice'], cs: ['nakrájet na plátky'] },
      { en: ['stir'], cs: ['míchat', 'zamíchat'] },
      { en: ['chop up'], cs: ['nasekat'] },
      { en: ['put something on'], cs: ['dát něco na'] },
      { en: ['afternoon tea'], cs: ['odpolední svačina'] },
      { en: ['barbecue'], cs: ['barbecue', 'grilování'] },
      { en: ['breakfast'], cs: ['snídaně'] },
      { en: ['course'], cs: ['cod'] },
      { en: ['cutlery'], cs: ['příbor'] },
      { en: ['dinner'], cs: ['zpravidla večeře', 'oběd'] },
      { en: ['lunch'], cs: ['oběd'] },
      { en: ['meal'], cs: ['jídlo'] },
      { en: ['packed lunch'], cs: ['obědový balíček'] },
      { en: ['picnic'], cs: ['piknik'] },
      { en: ['snack'], cs: ['přesnídávka', 'svačina'] },
      { en: ['light snack'], cs: ['lehká svačina'] },
      { en: ['supper'], cs: ['večeře'] },
      { en: ['calorie'], cs: ['kalorie'] },
      { en: ['diet'], cs: ['dieta', 'strava'] },
      { en: ['vegatarian diet'], cs: ['vegetariánská dieta', 'vegetariánská strava'] },
      { en: ['fattening'], cs: ['kalorický'] },
      { en: ['healthy'], cs: ['zdravé'] },
      { en: ['mineral'], cs: ['minerálnní látka'] },
      { en: ['vitamin'], cs: ['vitamín'] },
      { en: ['weight'], cs: ['váha'] },
      { en: ['be fussy'], cs: ['být vybíravý'] },
      { en: ['be on a diet'], cs: ['držet dietu'] },
      { en: ['clear the table'], cs: ['sklidit ze stolu'] },
      { en: ['cook a meal'], cs: ['uvařit jídlo'] },
      { en: ['do the washing-up'], cs: ['umýt nádobí'] },
      { en: ['eat junk food'], cs: ['jíst nezdravé jídlo'] },
      { en: ['go on a diet'], cs: ['začít držet dietu'] },
      { en: ['grab a coffee'], cs: ['zhltnout kávu'] },
      { en: ['grab a bito to eat'], cs: ['dát si rychle něco k jídlu'] },
      { en: ['have a meal'], cs: ['dát si jídlo'] },
      { en: ['have a sweet tooth'], cs: ['být na sladké'] },
      { en: ['have an appetite'], cs: ['mít chuť k jídlu'] },
      { en: ['high in something'], cs: ['obsahovat v sobě hodně něčeho'] },
      { en: ['lay the table'], cs: ['prostřít stůl'] },
      { en: ['lose weight'], cs: ['zhubnout'] },
      { en: ['low in something'], cs: ['obsahovat málo něčeho'] },
      { en: ['put on weight'], cs: ['přibrat'] },
      { en: ['vegetarian food'], cs: ['vegetariánské jídlo'] },
      { en: ["watch one's weight"], cs: ['sledovat svou váhu', 'hlídat svou váhu'] },
      { en: ['bill'], cs: ['účet'] },
      { en: ['buffet car'], cs: ['jídelní vůz'] },
      { en: ['café'], cs: ['kavárna'] },
      { en: ['canteen', 'cafeteria'], cs: ['jídelna'] },
      { en: ['dish'], cs: ['jídlo', 'pokrm'] },
      { en: ['fast food restaurant'], cs: ['rychlé občersvení'] },
      { en: ['main course'], cs: ['hlavní chod'] },
      { en: ['menu'], cs: ['jídelní lístek'] },
      { en: ['napkin', 'serviette'], cs: ['ubrousek'] },
      { en: ['order'], cs: ['objednávka'] },
      { en: ['pub'], cs: ['hospoda'] },
      { en: ['self-service restaurant'], cs: ['samoobslužná restaurace'] },
      { en: ['service'], cs: ['obsluha'] },
      { en: ['starter'], cs: ['předkrm'] },
      { en: ['tablecloth'], cs: ['ubrus'] },
      { en: ['takeaway'], cs: ['jídlo s sebou'] },
      { en: ['tip'], cs: ['spropitné'] },
      { en: ['waiter'], cs: ['číšník'] },
      { en: ['waitress'], cs: ['servírka'] },
      { en: ['wine list'], cs: ['vinný lístek'] },
      { en: ['order'], cs: ['objednat'] },
      { en: ['serve'], cs: ['oblushovat'] },
      { en: ['book a table'], cs: ['zarezervovat stůl'] },
      { en: ['eat out'], cs: ['jíst v restauraci'] },
      { en: ['leave a tip'], cs: ['nechat spropitné'] }
    ]
  },
  {
    name: "Chapter 7",
    words: [
      { en: ['antique shop'], cs: ['starožitnictví'] },
      { en: ["baker's", 'bakery'], cs: ['pekařství'] },
      { en: ['bookshop'], cs: ['knihupectví'] },
      { en: ['boutique'], cs: ['butik'] },
      { en: ["butcher's"], cs: ['řeznictví'] },
      { en: ['chain store'], cs: ['obchodní řetězec'] },
      { en: ['charity shop'], cs: ['prodejna charity'] },
      { en: ["chemist's", 'pharmacy'], cs: ['lékarna'] },
      { en: ['clothes shop'], cs: ['obchod s oděvy'] },
      { en: ['delicatessen'], cs: ['lahůdky'] },
      { en: ['department store'], cs: ['obchodní dům'] },
      { en: ['DIY store'], cs: ['obchod s potřebami pro kutily'] },
      { en: ['fashion boutique'], cs: ['butik s módním zbožím'] },
      { en: ["fishmonger's"], cs: ['prodejna ryb'] },
      { en: ["florist's", 'flower shop'], cs: ['květinářství'] },
      { en: ['furniture shop'], cs: ['obchod s nábytkem'] },
      { en: ['garden centre'], cs: ['zahradnické centrum'] },
      { en: ["greengrocer's", 'fruit and veg shop'], cs: ['obchod s ovocem a zeleninou'] },
      { en: ['hardware shop'], cs: ['železářství'] },
      { en: ['health food shop'], cs: ['obchod se zdravou výživou'] },
      { en: ["jeweller's"], cs: ['klenotnictví'] },
      { en: ['market'], cs: ['trh', 'tržiště'] },
      { en: ["farmers' market"], cs: ['farmářský trh'] },
      { en: ['music shop'], cs: ['obchod s hudebninami'] },
      { en: ["newsagent's"], cs: ['novinový stánek', 'trafika'] },
      { en: ['off-licence'], cs: ['prodejna alkoholických nápojů'] },
      { en: ['pet shop'], cs: ['chovatelské potřeby'] },
      { en: ['second-hand shop'], cs: ['obchod s použitým zbožím', 'bazar'] },
      { en: ['shoe shop'], cs: ['obchod s obuví'] },
      { en: ['shopping centre', 'shipping mall'], cs: ['nákupní centrum'] },
      { en: ['sports shop'], cs: ['sportovní zboží'] },
      { en: ["stationer's"], cs: ['papírnictví'] },
      { en: ['supermarket'], cs: ['supermarket'] },
      { en: ['aisle'], cs: ['ulička mezi regály'] },
      { en: ['bar code'], cs: ['čárový kód'] },
      { en: ['basket'], cs: ['košík'] },
      { en: ['checkout', 'till'], cs: ['pokladna'] },
      { en: ['checkout assistant', 'cashier'], cs: ['pokladní'] },
      { en: ['convenience food'], cs: ['hotová jídla'] },
      { en: ['conveyor belt'], cs: ['pohyblivý pás u pokladny'] },
      { en: ['pet food'], cs: ['krmivo pro domácí mazlíčky'] },
      { en: ['shelf'], cs: ['police', 'regál'] },
      { en: ['tinned food'], cs: ['konzervy'] },
      { en: ['toiletries'], cs: ['toaletní potřeby'] },
      { en: ['trolley'], cs: ['nákupní vozík'] },
      { en: ['baby chaing facilities'], cs: ['prostory pro přebalování dětí'] },
      { en: ['cheap'], cs: ['levný'] },
      { en: ['choice'], cs: ['výběr'] },
      { en: ['counter'], cs: ['pult'] },
      { en: ['customer'], cs: ['zákazník'] },
      { en: ['department'], cs: ['oddělení'] },
      { en: ['escalator'], cs: ['eskalátor', 'pojízdné schody'] },
      { en: ['expensive'], cs: ['drahý'] },
      { en: ['for sale'], cs: ['na prodej'] },
      { en: ['on sale'], cs: ['ve výprodeji'] },
      { en: ['queue'], cs: ['fronta'] },
      { en: ['range of products'], cs: ['výběr', 'rozsah výrobků'] },
      { en: ['second-hand'], cs: ['použitý', 'zánovní'] },
      { en: ['shop assistant'], cs: ['prodavač'] },
      { en: ['shopaholic'], cs: ['člověk posedlý nakupováním'] },
      { en: ['shopper'], cs: ['nakupující'] },
      { en: ['shopping bag'], cs: ['nákupní seznam'] },
      { en: ['stall'], cs: ['stánek'] },
      { en: ['gift-wrap'], cs: ['zabalit jako dárek'] },
      { en: ['purchase'], cs: ['zakoupit'] },
      { en: ['queue'], cs: ['stát ve frontě'] },
      { en: ['Can I help you?'], cs: ['Mohu vám nějak pomoci?', 'Mohu vám nějak poradit?'] },
      { en: ['pick a product off a shelf'], cs: ['vybrat si zobží z regálu'] },
      { en: ['broken'], cs: ['rozbitý'] },
      { en: ['complaint'], cs: ['reklamace'] },
      { en: ['dissatisfied'], cs: ['nespokojený'] },
      { en: ['faulty'], cs: ['vadný', 'kazový'] },
      { en: ['past the sell-by date'], cs: ['s prošlým datem doporučeného prodeje'] },
      { en: ['receipt'], cs: ['účtenka', 'paragon'] },
      { en: ['replacement'], cs: ['výměna zboží'] },
      { en: ['return'], cs: ['vrátit'] },
      { en: ['scratched'], cs: ['poškrábaný'] },
      { en: ['exchange'], cs: ['vyměnit'] },
      { en: ['replace'], cs: ['nahradit'] },
      { en: ['work'], cs: ['fungovat', 'pracovat'] },
      { en: ['get a refund', 'get your money back'], cs: ['dostat zpátky peníze'] },
      { en: ['give refunds'], cs: ['vracet peníze'] },
      { en: ['keep crashing'], cs: ['stále nefungovat', 'opakovaně nefungovat'] },
      { en: ['make a complaint'], cs: ['reklamovat'] },
      { en: ['return something'], cs: ['take something back'] },
      { en: ['talk to the manager'], cs: ['promluvit si s vedoucím'] },
      { en: ['changing room', 'fitting room'], cs: ['zkušební kabinky'] },
      { en: ['designer clothes'], cs: ['značkové oblečení'] },
      { en: ['fashion'], cs: ['móda'] },
      { en: ['fashion accesories'], cs: ['módní doplňky'] },
      { en: ['fashion label'], cs: ['módní značka'] },
      { en: ['the latest fashions'], cs: ['poslední móda', 'nejnovější móda'] },
      { en: ['fashionable'], cs: ['módní'] },
      { en: ['label'], cs: ['značka'] },
      { en: ['designer label'], cs: ['návrhářská módní značka'] },
      { en: ["last year's model"], cs: ['loňský model'] },
      { en: ["men's wear"], cs: ['pánská móda'] },
      { en: ['outfit'], cs: ['oblčení', 'komplet'] },
      { en: ['size'], cs: ['velikost'] },
      { en: ['the right size'], cs: ['správna velikost'] },
      { en: ['too loose'], cs: ['příliš volný'] },
      { en: ['too small'], cs: ['příliš malý'] },
      { en: ['too tight'], cs: ['příliš těsný'] },
      { en: ['trendy'], cs: ['módní'] },
      { en: ["women's wear"], cs: ['dámská móda'] },
      { en: ['fit'], cs: ['dobře padnout', 'sedět'] },
      { en: ['match'], cs: ['hodit se'] },
      { en: ['suit'], cs: ['slušet'] },
      { en: ['go shopping'], cs: ['jít nakupovat'] },
      { en: ["I'm size 38"], cs: ['mám velikost 38'] },
      { en: ['look for something'], cs: ['hledat něco'] },
      { en: ['shop for clothes'], cs: ['nakupovat oblečení'] },
      { en: ['try something on'], cs: ['vyzkoušet si něco na sobě'] },
      { en: ['bank'], cs: ['banka'] },
      { en: ['car wash'], cs: ['automyčka'] },
      { en: ['daycare centre for children'], cs: ['zařízení denní péče o děti (školka', ' jesle)'] },
      { en: ["dry cleaner's"], cs: ['chemická čistírna'] },
      { en: ['eatery'], cs: ['jídelna'] },
      { en: ['food court'], cs: ['zóna s rychlým občerstvením', 'zóna s restaracemi'] },
      { en: ['garage'], cs: ['autoservis', 'garáž'] },
      { en: ["hairdresser's"], cs: ['kadeřnictví'] },
      { en: ['launderette'], cs: ['samoobslužná prádelna'] },
      { en: ['laundry'], cs: ['prádelna'] },
      { en: ['petrol station'], cs: ['čerpací stanice'] },
      { en: ["photographer's"], cs: ['fotograf'] },
      { en: ['post office'], cs: ['pošta'] },
      { en: ['service station'], cs: ['servisní stanice', 'autoservis'] },
      { en: ['services'], cs: ['služby'] },
      { en: ['shoe repairs'], cs: ['opravna obuvi'] },
      { en: ['50 per cent discount', '50 per cent off'], cs: ['padesátiprocentní sleva'] },
      { en: ['bergain'], cs: ['výhodná koupě'] },
      { en: ['deal'], cs: ['obchod', 'dohoda'] },
      { en: ['great reductions'], cs: ['velké snížení cen'] },
      { en: ['price'], cs: ['cena'] },
      { en: ['a fair price'], cs: ['rozumná cena'] },
      { en: ['half price'], cs: ['poloviční cena'] },
      { en: ['sale'], cs: ['výprodej'] },
      { en: ['special offer'], cs: ['výhodná cena'] },
      { en: ['on special offer'], cs: ['za výhodnou cenu'] },
      { en: ['be reduced from 100 pounds to 50 pounds'], cs: ['zlevněný ze 100 liber na 50'] },
      { en: ['buy something in a sale'], cs: ['koupit něco ve výprodeji'] },
      { en: ['buy two', ' get one free'], cs: ['dva za cenu jednoho'] },
      { en: ['ATM (automatic teller machine)', 'cash machine'], cs: ['bankomat'] },
      { en: ['cash'], cs: ['hotovost'] },
      { en: ['cheque'], cs: ['šek'] },
      { en: ['credit card'], cs: ['kreditní karta'] },
      { en: ['pay'], cs: ['platit'] },
      { en: ['accept credit cards', 'take credit cards'], cs: ['přijímat karty', 'brát karty'] },
      { en: ['enter you PIN'], cs: ['vložit PIN'] },
      { en: ['get money out of a cash machine'], cs: ['vybrat peníze z bankomatu'] },
      { en: ['not have enough cash on oneself'], cs: ['nemít při sobě dostatečnou hotovost'] },
      { en: ['pay by cheque'], cs: ['platit šekem'] },
      { en: ['pay by credit card'], cs: ['platit kartou'] },
      { en: ['pay in cash'], cs: ['platit hotově'] },
      { en: ['ad', 'advert', 'advertisement'], cs: ['reklama'] },
      { en: ['advertising campaign'], cs: ['reklamní kampaň'] },
      { en: ['billboard', 'hoarding'], cs: ['billboard'] },
      { en: ['brand', 'make'], cs: ['značka'] },
      { en: ['brand name'], cs: ['obchodní značka'] },
      { en: ['brochure'], cs: ['reklamní brožura'] },
      { en: ['classified ad'], cs: ['reklamní inzerát'] },
      { en: ['commercial'], cs: ['televizní reklama', 'rozhlasová reklama'] },
      { en: ['jingle'], cs: ['znělka'] },
      { en: ['leaflet'], cs: ['leták'] },
      { en: ['logo'], cs: ['logo'] },
      { en: ['peer pressure'], cs: ['vliv vrstevníků', 'tlak vrstevníků'] },
      { en: ['poster'], cs: ['plakát'] },
      { en: ['slogan'], cs: ['reklamní heslo', 'slogan'] },
      { en: ['advertise'], cs: ['propagovat', 'dělat reklamu'] },
      { en: ['attract the crowds'], cs: ['lákat davy'] },
      { en: ['place an advertisement'], cs: ['uveřejnit reklamu'] },
      { en: ['consumer'], cs: ['spotřebitel'] },
      { en: ['consumer society'], cs: ['konzumní společnost'] },
      { en: ['consumerism'], cs: ['konzumerizmus', 'zaměření na spotřebu'] },
      { en: ['consumption'], cs: ['spotřeba'] },
      { en: ['free market'], cs: ['volný trh'] },
      { en: ['goods'], cs: ['zboží'] },
      { en: ['product'], cs: ['výrobek'] },
      { en: ['profit'], cs: ['zisk'] },
      { en: ['protectionism'], cs: ['ochranářství', 'celní ochrana'] },
      { en: ['trade'], cs: ['obchod'] },
    ]
  }
];

interface IWord {
  name?: string;
  en?: string[];
  cs?: string[];
  audio?: number[];
  words?: IWord[];
  uuid?: string;
  parent?: IWord;
}

function tree(array: IWord[], parent?: IWord) {
  let rows: any[] = [];

  array.forEach((node, index) => {
    if (typeof node.name !== "undefined") {
      node.uuid = v1();
      node.parent = parent;
    }

    if (typeof node.words !== "undefined") {
      rows.push(...tree(node.words, node));
    }
  });

  return rows;
}

tree(words);
