export const words = [
  { en: ['attic', 'loft'], cs: ['podkroví', 'půda'] },
  { en: ['balcony'], cs: ['balkon'] },
  { en: ['basement', 'cellar'], cs: ['suterén', 'sklep'] },
  { en: ['boiler room'], cs: ['technická místnost', 'kotelna'] },
  { en: ['ceiling'], cs: ['strop'] },
  { en: ['chimney'], cs: ['komín'] },
  { en: ['dressing room'], cs: ['šatník'] },
  { en: ['door'], cs: ['dveře'] },
  { en: ['back door'], cs: ['zadní dveře'] },
  { en: ['front door'], cs: ['vstupní dveře'] },
  { en: ['downstairs'], cs: ['přízemí'] },
  { en: ['drive'], cs: ['příjezdová cesta'] },
  { en: ['fence'], cs: ['plot'] },
  { en: ['floor'], cs: ['patro', 'podlaha'] },
  { en: ['garage'], cs: ['garáž'] },
  { en: ['underground garage'], cs: ['podzemní garáž'] },
  { en: ['garden'], cs: ['zahrada'] },
  { en: ['front garden'], cs: ['předzahrádka'] },
  { en: ['rear garden'], cs: ['zahrada za domem'] },
  { en: ['gate'], cs: ['vrata'] },
  { en: ['laundry'], cs: ['prádelna'] },
  { en: ['lawn'], cs: ['trávník'] },
  { en: ['letterbox'], cs: ['schránka na poštu'] },
  { en: ['roof'], cs: ['střecha'] },
  { en: ['staircase'], cs: ['schodiště'] },
  { en: ['stairs'], cs: ['schody'] },
  { en: ['toilet'], cs: ['toaleta'] },
  { en: ['upstairs'], cs: ['patro', 'horní podlaží'] },
  { en: ['WC'], cs: ['WC'] },
  { en: ['window'], cs: ['okno'] },
  { en: ['blind'], cs: ['roleta', 'žaluzie'] },
  { en: ['central heating'], cs: ['ústřední topení'] },
  { en: ['curtain'], cs: ['závěs', 'záclona'] },
  { en: ['doorbell'], cs: ['zvonek u dveří'] },
  { en: ['doormat'], cs: ['rohožka'] },
  { en: ['electrical appliances'], cs: ['elektrický spotřebič'] },
  { en: ['fitted carpet'], cs: ['celoplošný koberec'] },
  { en: ['fitting'], cs: ['instalace', 'armatura'] },
  { en: ['furniture'], cs: ['nábytek'] },
  { en: ['hall'], cs: ['předsíň'] },
  { en: ['household appliances'], cs: ['domácí spotřebiče'] },
  { en: ['light'], cs: ['lampa', 'světlo'] },
  { en: ['light bulb'], cs: ['žárovka'] },
  { en: ['net curtain'], cs: ['záclona'] },
  { en: ['plant'], cs: ['rostlina'] },
  { en: ['radiator'], cs: ['radiátor', 'topení'] },
  { en: ['vacuum cleaner'], cs: ['vysavač'] },
  { en: ['wallpaper'], cs: ['tapeta'] },
  { en: ['windowsill'], cs: ['okenní parapet'] },
  { en: ['bath'], cs: ['vana'] },
  { en: ['bathroom'], cs: ['koupelna'] },
  { en: ['mirror'], cs: ['zrcadlo'] },
  { en: ['shower'], cs: ['sprcha'] },
  { en: ['soap'], cs: ['mýdlo'] },
  { en: ['tap'], cs: ['kohoutek'] },
  { en: ['toothbrush'], cs: ['zubní kartáček'] },
  { en: ['towel'], cs: ['ručník'] },
  { en: ['washbasin'], cs: ['umyvadlo'] },
  { en: ['washing machine'], cs: ['pračka'] },
  { en: ['bed'], cs: ['postel'] },
  { en: ['bedding'], cs: ['ložní prádlo'] },
  { en: ['bedroom'], cs: ['ložnice'] },
  { en: ['bedside table'], cs: ['noční stolek'] },
  { en: ['blanket'], cs: ['přikrývka'] },
  { en: ['bookshelf'], cs: ['police na knihy'] },
  { en: ['chair'], cs: ['židle'] },
  { en: ['mattress'], cs: ['matrace'] },
  { en: ['pillow'], cs: ['polštář'] },
  { en: ['rug'], cs: ['kobereček'] },
  { en: ['sheet'], cs: ['prostěradlo'] },
  { en: ['shelf'], cs: ['police'] },
  { en: ['wardrobe'], cs: ['šatník'] },
  { en: ['armchair'], cs: ['křeslo'] },
  { en: ['audio system', 'stereo'], cs: ['stereo zařízení'] },
  { en: ['bookcase'], cs: ['knihovna'] },
  { en: ['carpet'], cs: ['koberec'] },
  { en: ['CD player'], cs: ['CD přehrávač'] },
  { en: ['coffee table'], cs: ['konferenční stolek'] },
  { en: ['couch', 'sofa'], cs: ['pohovka'] },
  { en: ['cushion'], cs: ['polštářek'] },
  { en: ['dinning table'], cs: ['jídelní stůl'] },
  { en: ['fireplace'], cs: ['krb'] },
  { en: ['living room', 'sitting room'], cs: ['obývací pokoj'] },
  { en: ['TV set'], cs: ['televize'] },
  { en: ['cooker'], cs: ['sporák'] },
  { en: ['electric cooker'], cs: ['elektrický sporák'] },
  { en: ['crockery'], cs: ['porcelánové (stolní) nádobí'] },
  { en: ['cupboard'], cs: ['skříňka'] },
  { en: ['cutlery'], cs: ['příbory'] },
  { en: ['dishwasher'], cs: ['myčka'] },
  { en: ['freezer'], cs: ['mrazák'] },
  { en: ['fridge'], cs: ['lednička'] },
  { en: ['kettle'], cs: ['konvice'] },
  { en: ['electric kettle'], cs: ['varná konvice'] },
  { en: ['kitchen'], cs: ['kuchyně'] },
  { en: ['kitchen table'], cs: ['kuchyňský stůl'] },
  { en: ['microwave oven'], cs: ['mikrovlnná trouba'] },
  { en: ['oven'], cs: ['trouba'] },
  { en: ['running water'], cs: ['tekoucí voda'] },
  { en: ['sink'], cs: ['dřez'] },
  { en: ['teapot'], cs: ['konvice na čaj'] },
  { en: ['apartment', 'flat'], cs: ['byt'] },
  { en: ['bedsit'], cs: ['obývací ložnice'] },
  { en: ['double bedsit'], cs: ['obývací ložnice pro dvě osoby'] },
  { en: ['block of flats'], cs: ['bytový dům'] },
  { en: ['bungalow'], cs: ['přízemní domek'] },
  { en: ['cottage'], cs: ['chalupa', 'chata'] },
  { en: ['detached house'], cs: ['samostatný dům'] },
  { en: ['farmhouse'], cs: ['usedlost', 'zemědělské stavení'] },
  { en: ['high rise', 'towerblock'], cs: ['věžák'] },
  { en: ['mansion'], cs: ['sídlo', 'velký obytný dům'] },
  { en: ['office building'], cs: ['kancelářská budova'] },
  { en: ['residential building'], cs: ['obytná budova'] },
  { en: ['semi-detached house'], cs: ['dvojdomek'] },
  { en: ['skyscraper'], cs: ['mrakodrap'] },
  { en: ['studio flat'], cs: ['garsonka'] },
  { en: ['terraced house'], cs: ['řadový dům'] },
  { en: ['two-roomed flat'], cs: ['dvoupokojový byt'] },
  { en: ['accommodation'], cs: ['ubytování'] },
  { en: ['bill'], cs: ['účet', 'poplatek'] },
  { en: ['electricity bill'], cs: ['poplatek za elektřinu'] },
  { en: ['excluding bills'], cs: ['poplatky navíc'] },
  { en: ['including bills'], cs: ['poplatky zahrnuté v ceně'] },
  { en: ['telephone bill'], cs: ['účet za telefon'] },
  { en: ['estate agent'], cs: ['realitní makléř'] },
  { en: ['flatmate'], cs: ['spolubydlící (v bytě)'] },
  { en: ['for sale'], cs: ['na prodej'] },
  { en: ['landlady'], cs: ['domácí', 'majitelka bytu'] },
  { en: ['landlord'], cs: ['domácí', 'majitel bytu'] },
  { en: ['per month'], cs: ['měsíčně'] },
  { en: ['per week'], cs: ['týdně'] },
  { en: ['reasonable price'], cs: ['přijatelná cena'] },
  { en: ['rent'], cs: ['nájem'] },
  { en: ['roommate'], cs: ['spolubydlící (v pokoji)'] },
  { en: ['tenant'], cs: ['nájemník'] },
  { en: ['to let'], cs: ['k pronájmu'] },
  { en: ['can afford something', 'could afford something'], cs: ['moci si něco dovolit (finančně)'] },
  { en: ['find a place of your own'], cs: ['najít si vlastní bydlení'] },
  { en: ['let a flat'], cs: ['pronajmout byt'] },
  { en: ['pay in advance'], cs: ['zaplatit předem'] },
  { en: ['pay the bills'], cs: ['platit poplatky'] },
  { en: ['pay the rent'], cs: ['platit nájem'] },
  { en: ['rent a flat'], cs: ['pronajmout si byt'] },
  { en: ['share a flat', 'share a room'], cs: ['bydlet společně v bytě', 'bydlet společně v pokoji'] },
  { en: ['amenities', 'facilities'], cs: ['vybavenost', 'infrastruktura'] },
  { en: ['area'], cs: ['oblast'] },
  { en: ['capital', 'capital city'], cs: ['hlavní město'] },
  { en: ['city'], cs: ['velkoměsto'] },
  { en: ['conveniently located'], cs: ['výhodně situovaný'] },
  { en: ['countryside', 'the country', 'village'], cs: ['venkov'] },
  { en: ['district'], cs: ['oblast'] },
  { en: ['easy access to something'], cs: ['snadný přístup k něčemu'] },
  { en: ['home town'], cs: ['domovské město'] },
  { en: ['housing estate'], cs: ['sídliště'] },
  { en: ['inhabitant', 'resident'], cs: ['obyvatel'] },
  { en: ['location'], cs: ['poloha', 'umístění'] },
  { en: ['neighbour'], cs: ['soused'] },
  { en: ['neighbourhood'], cs: ['okolí'] },
  { en: ['old town'], cs: ['staré město'] },
  { en: ['public transport'], cs: ['hromadná doprava'] },
  { en: ['rural'], cs: ['venkovský'] },
  { en: ['slums'], cs: ['slumy'] },
  { en: ['suburbs'], cs: ['předměstí'] },
  { en: ['tourist resort'], cs: ['turistické středisko'] },
  { en: ['tourist town'], cs: ['turistické město'] },
  { en: ['town'], cs: ['město'] },
  { en: ['underground station'], cs: ['stanice metra'] },
  { en: ['urban'], cs: ['městský'] },
  { en: ['view off'], cs: ['vyhlídka', 'výhled'] },
  { en: ['ancient'], cs: ['starožitný', 'starodávný'] },
  { en: ['bare'], cs: ['holý'] },
  { en: ['bright'], cs: ['jasný'] },
  { en: ['comfortable'], cs: ['pohodlný'] },
  { en: ['uncomfortable'], cs: ['nepohodlný'] },
  { en: ['cosy'], cs: ['útulný'] },
  { en: ['fitted kitchen'], cs: ['kuchyně na míru'] },
  { en: ['furnished'], cs: ['zařízený'] },
  { en: ['unfurnished'], cs: ['nezařízený'] },
  { en: ['in bad condition'], cs: ['ve špatném stavu'] },
  { en: ['in good condition'], cs: ['v dobrém stavu'] },
  { en: ['modern'], cs: ['moderní'] },
  { en: ['recently renovated'], cs: ['nedávno zrenovovaný'] },
  { en: ['roomy', 'spacious'], cs: ['prostorný'] },
  { en: ['tiny'], cs: ['maličký'] },
  { en: ['collapse', 'fall down'], cs: ['zhroutit se'] },
  { en: ['DIY', 'Do it yourself'], cs: ['udělej si sám'] },
  { en: ["do up one's house", 'redecorate'], cs: ['vylepšovat dům', 'nově vymalovat'] },
  { en: ['clean'], cs: ['mýt', 'čistit'] },
  { en: ['commute'], cs: ['dojíždět do práce'] },
  { en: ['cook'], cs: ['vařit'] },
  { en: ['vacuum'], cs: ['luxovat'] },
  { en: ['be at home', 'be in home'], cs: ['být doma'] },
  { en: ['clean the bathroom'], cs: ['umýt koupelnu'] },
  { en: ['clean the floors'], cs: ['umýt podlahy'] },
  { en: ['clean the windows'], cs: ['umýt okna'] },
  { en: ['clean up the mess'], cs: ['uklidit nepořádek'] },
  { en: ['do the cooking'], cs: ['vařit'] },
  { en: ['do the dishes', 'do the washing-up'], cs: ['mýt nádobí'] },
  { en: ['do the housework', 'do household jobs'], cs: ['dělat domácí práce'] },
  { en: ['do the ironing'], cs: ['žehlit'] },
  { en: ['do the shopping'], cs: ['nakupovat'] },
  { en: ['do the washing'], cs: ['prát'] },
  { en: ['feel homesick'], cs: ['stýskat si po domově'] },
  { en: ['get home'], cs: ['dostat se domů'] },
  { en: ['leave the house'], cs: ['odejít z domu'] },
  { en: ['lock the door'], cs: ['zamknout dveře'] },
  { en: ['make the beds'], cs: ['stlát postele'] },
  { en: ['move house'], cs: ['přestěhovat se'] },
  { en: ['move in'], cs: ['nastěhovat se'] },
  { en: ['move out'], cs: ['vystěhovat se'] },
  { en: ["put away one's clothes"], cs: ['uklidit si oblečení'] },
  { en: ['see somebody home'], cs: ['vyprovodit někoho domů'] },
  { en: ['stay in'], cs: ['zůstat doma'] },
  { en: ['stay out'], cs: ['zůstat venku'] },
];
